### ISSUE TITLE
Rename src/histogram/accumulators.cpp to src/register_accumulators.cpp etc

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#101]
It is generally a good idea to call a file after the class or function if the file only includes a single class or function. For me it would be much more logical to rename accumulators and the other implementation files to register_something so it matches the functions in these files.

**Comment by HDembinski** [comment]
It would make it easier to navigate to the right file in Atom, for example.

**Comment by henryiii** [comment]
Sure, the names of these files is not something I necessarily thought much about and should be clear/consistent.

**Comment by henryiii** [comment]
(Technichally this is an "enhancement", and not a 0.50 milestone requirement, as it doesn't change the API, but it's easy and I'd like it done sooner rather than later.)
