### ISSUE TITLE
Remove storage interface

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#102]
The storage classes have some interface exposed in Python. I would like to remove this. Neither users nor our tests should touch the storage directly. The storage implementation is tested in boost::histogram, so there is no need to test it in Python. Furthermore, storage functionality can always be tested indirectly by testing a histogram that uses this storage.

I don't want any interface exposed on the storages except their constructor. Exposing more is giving users wrong ideas. In general, we have to be stingy with public interface, because everything that is exposed as public we cannot change easily later. Therefore, it is better to expose as little as possible, so we maintain as much flexibility as possible in changing things.

**Comment by henryiii** [comment]
Agreed, probably was just trying to wrap as much as possible at that point.

**Comment by henryiii** [comment]
> Therefore, it is better to expose as little as possible, so we maintain as much flexibility as possible in changing things.

:+1:

**Comment by henryiii** [comment]
Actually, the reason this is here is to allow storage pickling to be unit-tested in Python. Pickling is not tested by boost::histogram, and testing a histogram that uses the storage is an integration test, not a unit test. I can drop it, but I like being able to do the unit test. How about renaming `push_back` to `_push_back`?

**Comment by HDembinski** [comment]
If you test the pickling of the histogram, it also implicitly test the pickling of the storage. That would be my preference if there is no issue with that I cannot see at the moment.

**Comment by HDembinski** [comment]
> testing a histogram that uses the storage is an integration test, not a unit test.

Where you draw the line between these is a bit arbitrary. The histogram class itself is still a unit. The storage is a replaceable component of the histogram, but it has no use on its own. In my understanding, an integration test is about interactions between different independent classes. There is no interaction here, because a storage is a component, it is not an independent class.

Despite the semantics, I

**Comment by henryiii** [comment]
How about removing the `__set/getitem__` and making those private too (would just need a single `_get`)? Since serialization treats storage as a separate unit, I really would like some way to test it without testing all the rest of histogram too. We save time if we know what is broken immediately from the test.

**Comment by henryiii** [comment]
Actually, is there a way to get the storage from a histogram? If we could have `_storage`, then I could pop the storage off and test picking it; would only need `==`.

**Comment by henryiii** [comment]
If not, I'll kill the test and just not have a unit test for storage pickling. The current one doesn't work for unlimited storage, which makes it less useful as a unit test.

**Comment by henryiii** [comment]
(Note: we still can and should test pickling an empty storage instance. A user should be able to write `s = bh.storage.unlimited()`, then pickle it and unpickle it (for example, in multiprocessing before Python 3.8 comes out). `s = bh.storage.unlimited` already works for free. :)

**Comment by HDembinski** [comment]
Why should a user be able to pickle an isolated storage instance? I think this should not work. I think people should only pickle histograms.

**Comment by henryiii** [comment]
I just gave an example. Python uses pickle to transfer objects in multiprocessing. (Avoidable in Python 3.8, I believe). All objects should be picklable unless they are io or network related.

**Comment by HDembinski** [comment]
I think you shouldn't regard a storage as an independent entity. It is only a component of an entity, which is the histogram. The storage is not designed to be useful on its own. Therefore, I think you principled argument doesn't apply.

> Actually, is there a way to get the storage from a histogram?

Technically, yes, with `bh::unsafe_access`, but this is intentionally not part of the interface that a normal user should touch.

Regarding the pickling for multiprocessing, here you don't pickle the storage but the whole histogram anyway. You need the axes to do anything useful with the histogram.

**Comment by henryiii** [comment]
Does the PR look fine now?

It's a good idea if all classes support being transferred in multiprocessing if they can (anything except IO or networking).

**Comment by HDembinski** [comment]
The storage doesn't have to be pickleable, but maybe that ok.

**Comment by henryiii** [comment]
Let me know if anything else is needed here!
