### ISSUE TITLE
Renaming axes::any

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#103]
I don't like the name `axes::any`, because the actual type is `std::vector<axis::variant<...>>`. I would prefer the name `axis_vector`. I think we can call this any way we like, because it is not exposed to Python. The problem is that `axes::any` does not clarify that this is a vector.

**Comment by henryiii** [comment]
Any sounds like type-erasure, which this is not, but vector is not very clear either, as it's a vector of variants. I always use plural to indicate that this is a vector; that is why this is an `axes` instead of `axis`.

**Comment by HDembinski** [comment]
It looks really awkward if the namespace declares whether you deal with a container or an element.

**Comment by HDembinski** [comment]
I would like the type aliases in boost-histogram to follow some pattern which makes it easy to see which types they correspond to in boost::histogram. `axes::any` is not doing that for several reasons. In C++, `any` refers to `void*` like object, which knows which type is stored behind the pointer, see std::any and boost::any. The name is highly misleading.

**Comment by henryiii** [comment]
I agree about the name `any`, as I indicated before. It looks like type-erasure, such as `std::any`. How about `axes::variant`? Or `axes::collection`? The later rather indicates it's a vector as well.

**Comment by henryiii** [comment]
PS: Since it's not exposed to Python, I'm not really against `axis_vector` either)

**Comment by HDembinski** [comment]
How about `axis_variant_vector`.

**Comment by henryiii** [comment]
I like that.
