### ISSUE TITLE
Rename storages

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#104]
I think that a type called `storage::double_`/`storage.double` looks quite weird in C++ and in Python. Since in C++ the storages are not put in a sub-namespace, they shouldn't be in boost-histogram, either. I would like to rename the C++ type to `double_storage` and likewise the corresponding Python type. The storages shouldn't be in their own submodule, because that's not how it is in C++ either. To not put them in a namespace was an intentional choice in C++. Whether it really was the right choice I don't know, but I want boost-histogram to be consistent with boost::histogram.

**Comment by henryiii** [comment]
We cannot reproduce the C++ interface here, because we must be fully compiled. The mapping is `bh::dense_storage<double>` == `bh.storage.double`, which is clear and simple, IMO. This also allows you to ask which storages are available in Python, which is `dir(bh.storage)` or `bh.storage.<tab>`, which is something that doesn't even make sense in the C++ version, as it is templated and you can make your own. We could rename "storage" to "dense_storage" to better mimic C++, but I vote for the shorter and simpler name (could be convinced otherwise).

Please ignore the `double_` in C++, that is just to stay consistent and reduce complexity in C++ bindings, it is not user facing.

**Comment by henryiii** [comment]
By the way, I recommend always starting with the general term, then the more specific one; I really regret every time I've not done this. Alphabetical sorting should put similar items together. For example, I used `azure_test_pipeline` and `azure_build_pipeline`, and now if I do an `ls`, they are not together. `azure_pipeline_*` would have been a much better scheme!

**Comment by HDembinski** [comment]
Ok, I see the point of `dir(bh.storage)` in Python. It still feels awkward to me to call something that is a whole container like one element of that container, e.g. `bh.storage.double`. I would prefer for educational reasons to have `bh.storage.double_storage` or `bh.storage.storage_double`. Another option which would also feel a bit less awkward is to use `bh.storage.dense_double`.

**Comment by HDembinski** [comment]
Just to clarify, I think the name `bh.storage.double` is ok, but if `storage` is a submodule, you can also do `from bh.storage import double` which I find very awkward.

**Comment by HDembinski** [comment]
> I recommend always starting with the general term, then the more specific one

I agree in principle. I had some reasons why I didn't do it for storage, but I don't recall them right now.

**Comment by henryiii** [comment]
You can do `from numpy import double`. `double` does not have special meaning in Python. However, int does; what about renaming `int` to `uint`? In general, I would not expect or recommend anyone import from the `storage` namespace, and if they did, they should know what they are doing. `bh.storage.double_storage` and `bh.storage.storage_double` look awful to me; what's the point of a namespace then? (Yes, I don't like ROOT's `ROOT::RDataFrame`, I would have much preferred `ROOT::DataFrame`)

**Comment by HDembinski** [comment]
Ok, you are right about `from numpy import double`, I forgot about that. I think that's ugly, but I see it is established. I agree that `bh.storage.storage_double` is not optimal. So what about `bh.storage.dense_double`?

**Comment by HDembinski** [comment]
My concern is about readability. `np.double` refers to a data type, but `bh.storage.double` refers not to a data type but to a collection of data types. The name should be different to emphasize this.

**Comment by HDembinski** [comment]
Also, the Python names need to bear a resemblance to the C++ names.

**Comment by henryiii** [comment]
I could live with `dense_double` (and `dense_*` for the other names).

**Comment by henryiii** [comment]
What about `dense_unlimited`, `dense_weight`, etc? Boost.Histogram drops the dense here. I would rather be consistent, so that would mean dropping the dense or adding a dense where B.H doesn't have it.

What about renaming the `storage` namespace to `dense_storage`? I like shorter names better, but that is possible. We are already asking users used to using strings for (what should be) enums in python (and things like `dtype='f8')` to do a lot just to select the storage on a histogram.

(Currently, we don't have any non-dense storage)

**Comment by henryiii** [comment]
`bh::dense_storage<double>` == `bh.dense_storage.double` does look nice.

**Comment by HDembinski** [comment]
I would prefer `bh.storage.dense_double`. I wouldn't overdo it with the submodules and I want the module structure to follow the namespace structure in boost::histogram. I may introduce a bh::storage namespace in boost::histogram, but I will not introduce a bh::dense_storage namespace.

**Comment by henryiii** [comment]
You did not explain what you want to do with `bh::weight_storage == dense_storage<accumulators::weighted_sum<>>` and similar typedefs. Would you be okay renaming them to `bh.storage.dense_weight`  in boost-histogram?

**Comment by HDembinski** [comment]
Yes, the idea was to either prefix everything that uses a dense storage, which right now is everything. Or not have a `dense_` prefix at all. I am coming around to the idea leaving the `dense_` prefix away. If at some point we introduce sparse storage, we can still have `dense_double` and `sparse_double` and `double`, the last being another name for `dense_double`.

In any case, `bh.storage.profile` has to be renamend to `bh.storage.mean` and `bh.storage.weighted_profile` to `bh.storage.weighted_mean`.

**Comment by henryiii** [comment]
Mean is much better than profile, IMO! Will change.

**Comment by henryiii** [comment]
(PS: Will Boost.Histogram offer typedefs without the profile name, too?)

**Comment by henryiii** [comment]
Please close if you are happy with the names, or let me know what you are interested having. I'm find with adding or leaving off the `dense_*` prefix, I can't say one is better than the other ATM.

**Comment by HDembinski** [comment]
> (PS: Will Boost.Histogram offer typedefs without the profile name, too?)

Maybe, I am thinking about it, along adding a `storage` namespace and adding separate includes for each storage to boost::histogram. Just to have boost.histogram and boost::histogram consistent.

**Comment by henryiii** [comment]
We probably should decide if we need to change it or if it's okay as is before the beta.
