### ISSUE TITLE
Sharing serialization implementation with boost::histogram

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#107]
I changed the implementation/serialization of `accumulators::mean` in develop. This may happen again at any time, which shows me that maintaining two serialization implementations is brittle. The serialization code is tricky to write, complex, and deeply tied to the implementations of the classes in C++, we need to find a way for boost-histogram to use the underlying implementation of boost::histogram.

The problem with the boost::histogram version right now is that it is hard-coded to use boost::serialization. In the long-term, this could be generalized, but in the short term, I think another solution is possible. Instead of adding boost::serialization to the externs, we could add some fake headers to this project which mimic paths and namespaces of boost::serialization on the surface so that the boost::histogram implementation of the serialization code works, while actually calling our stand-ins.

I would like to work on this for 0.5

**Comment by henryiii** [comment]
This would be great! I've already tried to design it so that there are as few changes as possible between the systems, so I bet this would be reasonably easy to do.

**Comment by henryiii** [comment]
(I'm calling this an enhancement rather than a 0.50 target because it's not user facing and not absolutely required. But it would be great if it made it in before 0.50!)

**Comment by henryiii** [comment]
This was completed with #166!
