### ISSUE TITLE
Fix the accumulator interface

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#115]
The `__init__` and `__call__` interface should be removed.

See arguments for storage interface.

**Comment by henryiii** [comment]
I think, while storage is not useful on its own, accumulators could be. One way to teach the library would be to demonstrate accumulators on their own before using them in histograms. Also, users can understand how the pieces work together if they can also see them work on their own. Finally, having accurate summing, etc. could be useful beyond histograms.

**Comment by HDembinski** [comment]
Or to be precise, the filling interface was not designed to be user-friendly. The interface to get information out of the accumulator was.

**Comment by HDembinski** [comment]
The accumulators should accept a weight as a keyword. The vectorization for the `__call__` operator looks wrong, this is not a mapping but a reduction. `bh.accumulators.mean([1, 2, 3])` should return `6`.

**Comment by HDembinski** [comment]
Actually, I should not return anything. The state of the accumulator is not always representable by a number. The accumulator state itself is the valid final state after the accumulation, so there is nothing to return.

**Comment by henryiii** [comment]
I think it should return itself, actually. When you call something, you expect it to return, and as you pointed out, the accumulator itself is the final state.

**Comment by HDembinski** [comment]
That would be similar to how iterators work, but not consistent with how Boost.Accumulators work, which return void, see https://www.boost.org/doc/libs/1_71_0/doc/html/boost/accumulators/accumulator_set.html
The accumulators in Boost.Histogram follow the design of the Boost.Accumulators. If there is no strong reason to change this, I would like to keep it consistent.

There are plenty of methods which return void, all setters for example. The insert method of std::set https://en.cppreference.com/w/cpp/container/set/insert does not return anything when a range of values is inserted. An accumulator that uses the call operator looks like a function, that is just for convenience, it is simply not a function but a functor. A functor does not have to return anything.

Practically speaking, I would like to see an example which shows that returning the accumulator itself is useful. For a C++ iterator, it is useful to return itself when it is modified so one can write things like `while (++iter != end) {...}`.

**Comment by henryiii** [comment]
I've got an idea, please ignore the following for now. I was showing how returning self could be useful, but due to the modifying behavior of the accumulators being nothing like anything else in Python, it might not be a good idea after all. And I think I might have a better suggestion later today.

---

~~In Python, returning None is never useful; while returning self allows methods to be chained. So, if you only cared about the value, you could do something like this:~~

```python
mean = bh.accumulators.mean()
vec = np.array((1,2,3,4,5,6))
result_value = mean(vec).value()
```

~~You could also avoid the ugly in-place change, at least visually~~

```python
result = mean(vec)
```

**Comment by HDembinski** [comment]
Ok, if you have an even better example, but method chaining already convinced me.

**Comment by henryiii** [comment]
The new version runs circles around the old version (really, it's about 3 times faster), and is much more Pythonic and more like the C++ version too. I've (mostly) changed the call operator into a smart constructor. So you can do:

```python
vec = np.array((1,2,3,4,5,6))
result = bh.accumulators.mean(vec)
print(result.value) # (etc)
```

You can use `+=` on a matching accumulator (which can be quite useful); just like in C++. If you want the one-at-a-time modifying behavior, you can use `+=` on doubles for the sum accumulators, and the mean accumulators support single item call operators that return self (not ideal Python, but not bad and symmetric with the C++ version - and usually avoidable now).

**Comment by HDembinski** [comment]
It is a deviation from C++, but seems useful. I worry about people using this in ways that we don't expect, but I don't have any specific arguments against. So it is fine by me.

**Comment by HDembinski** [comment]
Wait, if you use the constructor in this way, we cannot use it to prime the accumulator, to initialize it into a specific state. Your design is not future safe.

**Comment by henryiii** [comment]
The priming constructors are still there. They have more arguments so are not affected.

**Comment by henryiii** [comment]
Accumulators behave exactly like C++ now, so should be ready for 0.50 and teaching. We can discuss a way to vectorize later.
