### ISSUE TITLE
Increase to C++17 standard?

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#122]
It would simplify the code in several places if we could use C++17 in the wrapper. If we distribute binaries anyway, we could require this recent standard for the compilation. Is there a reason to stick to C++14?

**Comment by HDembinski** [comment]
Mostly, I would like to replace bh::detail::static_if with if constexpr, but there would be other benefits.

**Comment by henryiii** [comment]
I knew exactly what you were wanting it for. :) I *think* I would like to keep C++14 for the first release, then move up. That way, we can point users with older compilers and systems the binaries don’t cover toward the older release. Getting this to work with C++14 (especially for manylinux1) was quite a challenge.

*However*, most of that work applies equally well to C++17. The argument that non-manylinux systems tend to have newer compilers also applies to C++17.  Conda still was using Clang 4 until recently on Mac, but that has pretty good C++17 support. If we can’t come up with a common case having 14 but not 17, I’d be willing to risk it.

How have the binaries been working for iMinuit? Do you still have users compiling?

**Comment by HDembinski** [comment]
I don't know. :) I got no feedback regarding this. Perhaps should have done some advertisement. It is pretty awesome to have binary wheels.

**Comment by HDembinski** [comment]
I am good with your plan.

**Comment by henryiii** [comment]
Note: Python 2.7's Python.h header is not technically compatible with C++17 (though most compilers just issue a warning about the removal instead of blocking it). I'm not sure if one of the patch releases will or has fixed the problem, but since it's been in critical fixes only for a while, and dying in a few months, I wouldn't be surprised if it doesn't.

**Comment by HDembinski** [comment]
If you want we can close this. I am not a fan of issues that linger about for a long time, version 2.0.0 seems a bit in the future.

**Comment by henryiii** [comment]
Let's add this to the 2.0 release plan notes (on the milestone page), then we can close it. We should keep the drop 2.7 support issue, IMO, so people can have a place see the plan and to comment.

**Comment by henryiii** [comment]
(Added to the 2.0 description on GitHub)
