### ISSUE TITLE
Vectorize accumulators

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#129]
This is a placeholder for a discussion on the best way to provide a vectorized accumulator interface in Python. This is not directly mappable to C++ (since in C++ a loop is not 100x slower than an array, and C++14 does not really have anything like Numpy).

Possible options so far:

1. Something in the constructor

Possibly nicest Python interface: `bh.accumulor.sum(arr)` creates a pre-filled accumulator from an array.

2.  Specific vectorized function

Probably `bh.accumulor.sum().fill(arr)`, nice symmetry with Histograms.

3. Vectorized call operator

Make very ugly Python: `bh.accumulor.sum()(arr)`, does not play well with duck typing, and modifying a object with a call operator is very ugly (not: mean already has a 1-item call operator). I don't like the idea of adding call operators to sum, where C++ doesn't even have them.

4. Vectorized operators

Like the one above, but uses += arr for sum. It is not possible to add weights for weighted_sum, however.

**Comment by HDembinski** [comment]
> Make very ugly Python...

It is only ugly because you write it in one line. I don't know how often I have to tell you that accumulators are functors and not functions. You know what a functor is, right?

**I don't want accumulators exposed at all and I don't see why have this discussion at all.**

**Comment by HDembinski** [comment]
We don't need vectorized accumulators, because accumulators are not to be used by users. 

1. We don't expose accumuatlors. Problem solved.
2. We don't vectorize anything on accumulators. Problem solved.

You are creating these issues because you push for accumulators to be exposed in Python against my design intentions. Then you criticize compromises that I try to come up with against my better judgement. I am really quite fed up with this discussion.

**Comment by henryiii** [comment]
Option 2 solves your criticisms:

```python
s = bh.accumulor.sum()
s.fill(arr1)
s.fill(arr2)
s += 1
s += 2
```

```python
s = bh.accumulor.mean()
s.fill(arr1)
s.fill(arr2)
s(1)
s(2)
```

I gave you reasons:

> I think, while storage is not useful on its own, accumulators could be. One way to teach the library would be to demonstrate accumulators on their own before using them in histograms. Also, users can understand how the pieces work together if they can also see them work on their own. Finally, having accurate summing, etc. could be useful beyond histograms.

To which you replied:

> Ok, you convinced me

**Comment by HDembinski** [comment]
`.fill` is seems like the best option, at least it is symmetric.

Just for completeness, one could also have something like this:
```
data = [...]
from boost_histogram.accumulators import mean
# normal C++-like mean accumulator
m = mean()
for x in data:
    m(x)
print(m.value)

from boost_histogram.accumulators.vectorized import mean
mean_value = mean(data)
```

**Comment by henryiii** [comment]
I thought about that. I like having `.fill` for several reasons (mostly the symmetry with histogram, which also helps when teaching in Python, at least), but this would be the way some things in the standard library work. Pickle, json, subprocess all have "easy functions" and a separate class based interface. I think today most people are okay using (well designed) classes, but as I said, this is common in Python. I think that part should wait till we have a bit more time to work on "extras" - including a histogramNd function.

Would you like fill added for 0.5 or later? It's easy for me to add now if you want.

**Comment by henryiii** [comment]
I'd like to see where the different views of histograms go before deciding on details like if vectorized.mean returns an accumulator or a value (or something else).
