### ISSUE TITLE
`.at` Docstring update

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#134]
I'm adding `_at_set` so that the Python code can add `__setitem__`. We cannot support `h.at(i) = 2` (invalid Python syntax), whereas `[]` can - so that should probably be the replacement. 

Should we rename `at` to `_at_get`? Or should we try to provide a replacement? I'm think of the following:

```python
h.at(-1) = 3 # syntax error
```

We can do this using `[]` indexing:

```python
h[bh.underflow] = 3
```

But should there be a way to use `-1`? Should there be an `.at_set(3, -1)`, or `h[bh.at(-1)] = 3`? If we leave `.at` public, then `.at(-1)` does this, just setting is an issue.

**Comment by HDembinski** [comment]
We want to have `.at` because it also exists on the C++ side, and to allow `-1` to be used like in C++. So `at` should stay even with the caveats. At least it allows reading.

**Comment by henryiii** [comment]
I have an idea, how about a keyword-only argument `value=...`, that sets if present, otherwise it gets. It could always return the value at that bin for consistency. Inspired by the `np.histogram` idea.

**Comment by HDembinski** [comment]
> Please pick a name, then.

?? I was proposing to keep everything as is. `.at()` remains there but it is read-only. If you must set the value in Python, you use `h[bh.underflow]`.

**Comment by HDembinski** [comment]
We just need to document this in the docstring of `.at`

**Comment by henryiii** [comment]
Replaced by #155.
