### ISSUE TITLE
Print the compiler type and version in setup.py

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#169]
I don't know which compiler is used in each Azure build, and when only one of the builds fail, I need to look into that one. It would be great to see the compiler type and version that distutils uses to compile the code.

**Comment by henryiii** [comment]
This it not completely done - there is more information on the compile printed now, but getting more than this (compiler versions, for example) looks to be quite tricky without a fair amount of platform specific code and hacking distutils.

**Comment by henryiii** [comment]
Please reopen if you have an idea for how to add more to this!
