### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#173]
This is a placeholder fro dropping Python 2 support. (Plan may change depending on Scikit-HEP policy)

**Comment by hugovk** [comment]
On a similar topic, Matplotlib, scikit-learn, IPython, Jupyter, yt, SciPy, NumPy, and scikit-image have agreed:

* ["NEP 29 — Recommend Python and Numpy version support as a community policy standard"](https://numpy.org/neps/nep-0029-deprecation_policy.html#nep-29-recommend-python-and-numpy-version-support-as-a-community-policy-standard)

Where:

> This NEP recommends that all projects across the Scientific Python ecosystem adopt a common “time window-based” policy for support of Python and NumPy versions. Standardizing a recommendation for project support of minimum Python and NumPy versions will improve downstream project planning.

For example, they suggest:

> This project supports:
> 
> * All minor versions of Python released 42 months prior to the project, and at minimum the two latest minor versions.
> * All minor versions of  `numpy`  released in the 24 months prior to the project, and at minimum the last thee minor versions.

### Support Table

Date | Python | NumPy
-- | -- | --
Jan 07, 2020 | 3.6+ | 1.15+
Jun 23, 2020 | 3.7+ | 1.15+
Jul 23, 2020 | 3.7+ | 1.16+
Jan 13, 2021 | 3.7+ | 1.17+
Jul 26, 2021 | 3.7+ | 1.18+
Dec 26, 2021 | 3.8+ | 1.18+

### Drop Schedule

```
On next release, drop support for Python 3.5 (initially released on Sep 13, 2015)
On Jan 07, 2020 drop support for Numpy 1.14 (initially released on Jan 06, 2018)
On Jun 23, 2020 drop support for Python 3.6 (initially released on Dec 23, 2016)
On Jul 23, 2020 drop support for Numpy 1.15 (initially released on Jul 23, 2018)
On Jan 13, 2021 drop support for Numpy 1.16 (initially released on Jan 13, 2019)
On Jul 26, 2021 drop support for Numpy 1.17 (initially released on Jul 26, 2019)
On Dec 26, 2021 drop support for Python 3.7 (initially released on Jun 27, 2018)
```

The idea is these are the minimums, and to reduce maintenance burden on scientific projects, allowing them to worry less about dropping older Python versions, even if they're still supported by CPython itself.

**Comment by henryiii** [comment]
Dropping Python 3.6 in June seems very strong. 3.6 is still heavily used, due to difficulties with thte SSL transition, I think. I've started discussions in Scikit-HEP based on this document.

**Comment by henryiii** [comment]
Quick update for the record: Conda-forge has dropped Python 2 by default - you can specially request Python 2, but it's not there by default anymore. We probably will be tempted to re-add support for 2 for a little while for boost-histogram, since it would nice if Python 2 Conda users will get 0.8 and 1.0 and not be stuck at the current version. But it would be *even nicer* if we have no Python 2 users in Conda at all, so it might be best to wait and see if anyone asks for it.

(I've never got why people use Python 2 when they have Conda - I had a student come to me last year with a brand new project she had just started... In Python 2 Conda.)
