### ISSUE TITLE
Retrieving results of non-trivial storages

### ISSUE THREAD

**Issue by beojan** [scikit-hep/boost-histogram#175]
It doesn't seem to be possible to retrieve the results as a NumPy array when a non-trivial storage is used (e.g. `storage.weight`). It's known that `view` isn't supported, but `np.asarray` also crashes the Jupyter kernel.

**Comment by henryiii** [comment]
It is not currently possible - a decision has/had to be made about that the storages produce as a numpy array. I think we do have a plan now, but it has not been implemented yet. There is an incoming feature to Boost.Histogram C++ (I think today) that will help us here.

`h.view()` and` np.asarray(h)` use the same underlying machinery.

As a workaround, you can still iterate over the histogram cells and access them one-by-one as Python objects.

**Comment by beojan** [comment]
> a decision has/had to be made about that the storages produce as a numpy array

I would expect to be able to access each stored quantity as an array (i.e. `.values()` and `.variances()` as for individual cells in the C++ API).

**Comment by henryiii** [comment]
But then the returned item is no longer a numpy array (killing `.asarray`). We could possibly introduce a difference between `asarray` and `.view()` here, though.
