### ISSUE TITLE
Add functions to AxesTuple

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#176]
The functions on axes can generalize as well, and can be very useful values -> bins or bins -> values in one quick request, rather than calling each function one by one.

For example, on a 2D histogram:

```python
x, y = h.axes.index(a, b)
# VS
x = h.axes[0].index(a)
y = h.axes[1].index(b)
```

**Comment by HDembinski** [comment]
What became of "there should be one way to do it"? I think this is too much duplication.

**Comment by henryiii** [comment]
> there should be one way to do it

This means there should not be two identical ways to do something. It doesn't mean you can't provide something that someone could compute themselves. I chose are rather poor example, where I unpacked the result - often a user might not need an unpacked tuple, but will want coordinates.

What is the one way to do it now? If I have a ND histogram, I want to replace the current two ways to do it:

```python
xyz = [a.index(i) for a, i in zip(h.axes, abc)]
# OR
xyz = list(map(lambda a,i: a.index(i), zip(h.axes, abc)))
```

with one way to do it, the "right" way:

```python
xyz = h.axes.index(*abc)
```

Getting these can be useful (which is why I noticed the omission here). Since you can give a histogram `*abc` to fill, it makes sense that you might ask what the same `*abc` is in fractional bin coordinates, etc. This is naturally a function of the axes (since it does not require filled bins).

I also want consistency; any think on an axis can be called on axes to return all axes at once.

That's what I'm thinking anyway.

**Comment by HDembinski** [comment]
I agree that the function looks very elegant, but what do you do with these indices now?

**Comment by HDembinski** [comment]
I am asking because I don't understand why someone should want to transform a lot of values into indices. What is the use case? The public interface is our main handle nudge users into using the library correctly. By not adding certain things we can steer people away from doing that and rather do it the intended way.

**Comment by henryiii** [comment]
The same thing you do with the indices from the original axis function. In my current case, I'm using it to check to see which bin a value falls in, so that I can look in that bin to see if it was added there. (in this case, for teaching purposes, I'm also using `h[loc(...)]` and showing that they are the same)

The idea is that if something was useful enough to add to the `axis`, it should be available on `axes` as well.

**Comment by HDembinski** [comment]
People should use `h[loc(...)]` for that, so we don't need a second way of doing that.

**Comment by HDembinski** [comment]
> The idea is that if something was useful enough to add to the axis, it should be available on axes as well.

Well, I am not super against it. It looks very elegant, I admit that. For consistency, it make sense to add all the methods of the individual also to `.axes`.

**Comment by henryiii** [comment]
An axis should be able to convert between bin space and value space (and is does). A collection of axes should be able to do the same thing - that's the basis of a histogram. You can't see what `loc(...)` turns into, it's hidden. And I don't think anyone will be tempted to try to nest one in the other, `h[*h.axes.indexes(...)]` (and if they are that crazy, then they might as well write `h[h.axes[0].indexes(...), ...]` which they can do now).

But I think the strongest argument is constancy - "axes" can do anything "axis" can do, but on all axes at once. Makes it easier to teach when we don't have to add "except for...".

**Comment by HDembinski** [comment]
> And I don't think anyone will be tempted to try to ....

That is **exactly** what will happen when you add to many ways of doing the same thing. Anyway, for consistency's sake, I am already sold on this idea, but only because of that.

**Comment by henryiii** [comment]
Cute, `*` is not supported in `[]`, so Python keeps that from happening already! :)

**Comment by HDembinski** [comment]
Lucky you in this case, but I hope you see the general issue.

**Comment by HDembinski** [comment]
People will try to use our interface in million of ways that we cannot foresee. You, for example, in use boost::histogram in ways that I never intended. In general, "checking" whether things is the same is not what we support. The library should work and people shouldn't have to check things. We don't add public interface because it is comfortable for the developer, we add it when it is comfortable for the user.

**Comment by henryiii** [comment]
Yes, though in general intentionally limiting the interface to avoid users misusing it can have unintended consequences and should be applied carefully. You might stop a user who needs something you haven't foreseen from using your library at all; and no author foresees all possible applications of his or her library. If something is built out of components which have clear and well defined usages, users should be able to use them individually if reasonable.

(It's not wrong to limit in some cases, it just should be used carefully)

**Comment by HDembinski** [comment]
*sign* You have to have the last word, right?

Design is all about intentionally limiting the interface, to guide choices and to avoid mistakes. You don't want the "Launch nuclear missiles" button next to the "Order next coffee" button.

You were not trying to anticipate the needs of users with this feature. You suggested this interface to address your own needs, but you are a developer, not a user. I am just pointing this out. Is obvious that a more restricted interface offers less ways of unintentional misuse.
