### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#178]
Here's my current suggestion. Thoughts?

![BoostHistogramPythonGrad4](https://user-images.githubusercontent.com/4616906/67709240-f0fafc80-f993-11e9-9e69-ef0ffb07d625.png)

Follow up to https://github.com/boostorg/histogram/issues/200 .

**Comment by HDembinski** [comment]
Another improvement! Can the knot be made bigger so that it remains recognizable if the logo is scaled down? It would also give the composition more balance if the knot was roughly the same size as the python's head.

**Comment by henryiii** [comment]
![BoostHistogramPythonLogo](https://user-images.githubusercontent.com/4616906/67776167-57d0f200-fa36-11e9-8921-ed4047714bd1.png)

**Comment by HDembinski** [comment]
Perfect for me now, if you like it as well it is ready.

**Comment by henryiii** [comment]
I'm going to redo the H outline (convert strokes to paths, then fix seams), then it will be ready.

**Comment by henryiii** [comment]
Implemented! Enjoy.

**Comment by henryiii** [comment]
PS: The Inkscape source is in /docs/_src/images, that can be used to make a BW logo or extract the H outline.

**Comment by henryiii** [comment]
You can also now simply convert all fills to back, no strokes are used and the white parts all all hollow.

**Comment by HDembinski** [comment]
Thanks!
