### ISSUE TITLE
breaking change in boost::histogram's accumulators

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#182]
The develop branch just received a breaking change in the accumulator interface that users are not supposed to rely on, but it is public and boost-histogram relies on it. The change needs to be propagated to boost-histogram. The change was necessary because it fixes a critical issue with accumulators that can receive weights. There was an ambiguity where a sample could be used as a weights and vice versa without giving an error.

**Comment by henryiii** [comment]
The API is actually closer now between the two; boost-histogram already had weights as keyword only.

**Comment by henryiii** [comment]
Thanks for the heads up!

**Comment by HDembinski** [comment]
Thanks for the fast response and the quick fix. I would have submitted a patch today, but apparently it was clear enough for to resolve this. I am under pressure now because the gates are closing for Boost-1.72 and I really really want to have this in.
