### ISSUE TITLE
PEP 8 naming

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#187]
In [PEP 8](https://www.python.org/dev/peps/pep-0008/#class-names), Python classes are supposed to use CamelCase, with only the standard library or classes that are mostly called like functions as exceptions. Other than Numpy (which was making a basic type and originally targeting the standard library), most Python packages follow this convention (Pandas, iMinuit, Particle, Awkward, Matplotlib, etc.). Even more recent additions to the standard library follow this PEP 8 convention as well (Path from pathlib, ContextVar from contextvars, Enum from enum, etc.).

(Fun fact: it's actually enforced in Ruby by the language, you can't name a class starting with a lower case letter)

The proposal would be to make the Python classes CamelCase, with the PyBind11 and `cpp` classes lowercase, like in Boost.Histogram. (currently this is what is done, but it is hidden from the user by importing Histogram as histogram, Regular as regular, etc in `__init__.py/axis.py`). I *think* I would suggest that accumulators and storages remain lower-case, because they are more of a data-type than a full class (and are currently not pure Python classes).

**Comment by henryiii** [comment]
@HDembinski, I would need your full agreement on this to make the change.

**Comment by henryiii** [comment]
We could make the regular functions, such as `regular_pow` (also available currently as `regular.pow`) to be `Pow`, since the transformation functions really only make sense on regular binning, and `Pow` is obviously a class of some sort and not a function, like the `pow` function. it would inherit from `Regular`. (even if we don't use PEP 8 naming, inheritance is probably better than the class methods, now that I look at it again).

**Comment by HDembinski** [comment]
I am ok with the classes in Python using CamelCase, since we split the interface into `cpp` and Pythonic already in boost-histogram. In `cpp` they should have the `cpp` names.

I am not ok with shortening `regular_pow` to `Pow`. The transform should be a keyword argument on the regular axis class. 

```
from bh.axis import Regular
from bh.axis.transform import Log

Regular(10, 1, 3, transform=Log)
```

**Comment by henryiii** [comment]
This is *much* better. Because it's `Log` and not `log`, it clearly is not just handing in any function, which is why I've rejected such a design in the past.

And, it's not unreasonable that we could eventually add a class that accepts a Scipy C function pointer (which Numpy supports)? I am not very familiar with the interface, will have to look into it. We could also add a python callable, but the performance would be horrible - it would be better to show the use of a numpy function to produce a variable axis (no code in boost-histogram, just would be an example).

**Comment by henryiii** [comment]
The other thing I didn't like about it being a keyword when I've played with the idea is that it doesn't support all the other combinations of all the other keywords, which is somewhat implied by using keywords. You can't use Pow, turn off underflow, and turn on circular, for example. But we can throw an error in that case and already we have some invalid combinations even with grow.

**Comment by henryiii** [comment]
I just noticed this also fixes the ambiguity in setting a power with positional arguments:

```python
Regular(10, 1, 3, transform=Pow(1.5))
```

Now it's completely clear that the 1.5 is the power argument. I like it! PR incoming.

**Comment by HDembinski** [comment]
> And, it's not unreasonable that we could eventually add a class that accepts a Scipy C function pointer (which Numba supports)? I am not very familiar with the interface, will have to look into it. We could also add a python callable, but the performance would be horrible - it would be better to show the use of a numpy function to produce a variable axis (no code in boost-histogram, just would be an example).

I agree. I am not sure yet how this can be implemented, but we have at least the option by the interface.

**Comment by HDembinski** [comment]
> I just noticed this also fixes the ambiguity in setting a power with positional arguments

Exactly :)
