### ISSUE TITLE
Move reprs to Python

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#198]
Currently, we use reprs in C++. We should move those to Python; this will help them include the correct class name, and might be simpler to maintain in the long run.

We will need to improve the internal inspection capabilities a bit for this; currently you cannot get the power used for the regular with power transform.

@HDembinski originally had this idea.

**Comment by HDembinski** [comment]
The regular axis has a transform() method, which should be exposed as a read-only property. This can then be used to query the transform used and the power value in this case.

**Comment by henryiii** [comment]
Closed by #200.
