### ISSUE TITLE
Adaptive support of operators

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#20]
The `register_histogram_by_type` should statistically check what operations the histogram type supports and then enable only those. Infrastructure to achieve this is already implemented in boost::histogram and should be ported to boost-histogram, see
https://github.com/boostorg/histogram/blob/7301d6a4c2d2500245648388ab7a9709985a1f4f/include/boost/histogram/detail/meta.hpp#L137
and the following lines 215, 218, 221, 224, 227.

These would be used like so:

```
if (has_operator_rmul<histogram_t, double>::value)
   hist.def(py::self *= double());
```

**Comment by henryiii** [comment]
This was implemented in the atomics PR. It might be needed in a few more places though.

**Comment by henryiii** [comment]
And it has to be a constexper if, you’ll see in the current implementation.

**Comment by henryiii** [comment]
Implemented here:

https://github.com/scikit-hep/boost-histogram/blob/d4f0742da39e24dfffa8770cb2c8cd3d14ab06cd/src/histogram/histogram.cpp#L52-L54

@HDembinski, please look over the remaining operators and see if there are any other that could be conditional.
