### ISSUE TITLE
Transforms

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#203]
Now that we've finished with Storages, we need to discuss Tranforms. I'll keep it brief. I'll present 3 options, then @HDembinski , you select one and I'll implement it, no questions asked. My biased reasoning follows.

## Option 1

```python
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Log()) # Works
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Sqrt()) # Works
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Pow(2)) # Works
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Log) # Works
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Sqrt) # Works
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Pow) # Fails with Pow missing argument error
```

This is an interface that is easy to use correctly, hard to use incorrectly. If someone does not understand functors, they are not punished for missing the parentheses if no arguments are required. Note that Boost.Histogram *lets you skip adding a default initialized functor* if you specify it in the template:

```cpp
axis::regular<double, axis::transform::log> r_log{3, 10., 10000.};

using pow_trans = axis::transform::pow;
axis::regular<double, pow_trans> r_pow(pow_trans{1. / 3.}, 3, 1., 64.);
```

Note this option is the only one that gives you the correct error if Pow is used; it tries to call `Pow()`, which will give a required argument power missing error, rather than a generic error about uninitialized functors or such.

#### Option 1.a

A warning is issued if the parentheses are missed, but it still works.

## Option 2

```python
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Log()) # Works
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Sqrt()) # Works
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Pow(2)) # Works
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Log) # Fails
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Sqrt) # Fails
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Pow) # Fails
```

This is harder to use correctly, but still is clear. An explicit error could be thrown in the case a user forgets the parentheses.

## Option 3

```python
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Log()) # Works
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Sqrt()) # Works
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Pow(2)) # Works
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Log) # Fails
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Sqrt) # Fails
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.Pow) # Fails
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.log()) # Fails
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.sqrt()) # Fails
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.log) # Works
bh.histogram(bh.axis.regular(10,0,1), transform=bh.axis.transform.sqrt) # Works
```

This is harder to use correctly, and violates "there should be one way to do things" by duplicating functors that have no arguments. This is the most similar to the current design for storages, though, so familiarity may help.

#### Option 3.a

Also include `pow2`, `pow3`, for good measure.

---

@HDembinski select the one you feel is best, and I'll add it with no further comment.

**Comment by HDembinski** [comment]
I still believe that Option 3 is the most flexible and logical in the long run. It allows us to make pre-configured transforms, like pow2, without breaking the scheme. We can discuss it in the call later today.

**Comment by HDembinski** [comment]
I am always looking into the future and I am trying hard to avoid a design that may seem like a good solution now but will become limiting and awkward in the future. I already made a lot of mistakes like this in Boost.Histogram, the current version is the third rewrite from scratch.

**Comment by henryiii** [comment]
I have an interesting proposal, actually, that isn't too horrible with option 3. Let's discuss later today.

**Comment by henryiii** [comment]
Here's my proposal for transforms, first draft:

1. We add `CppTransform(cpp_function)`, and `PythonTransform(python_function)`, that take a compiled function and Python function, respectively. (I've not done this in Pybind11 before, but it looks pretty easy, and you have experience with it in iMinuit that I might call on ;) )
2. We add a base argument to Log. Then we set `log10 = Log(10)`, and `ln=Log(math.exp(1))`.
3. We remove `Sqrt()`. We set `sqrt = Pow(0.5)`.


Now, we have no name duplication based on capital letters, we have clear distinctions, and we have more functionality (even without number 1), and one less C++ axis (again, without number 1).

**Comment by henryiii** [comment]
Don't focus on the names too much; `CppTransform` is a terrible name. You might pass in a Numba function, which never makes it to C++.

**Comment by henryiii** [comment]
We'll have to make a backward incompatible change to pickling, but a) we already are doing that and b) pickle is actively discouraged by the Python community as a long term storage solution, so people are not supposed to be holding on to lots of pickles. It's mostly for transfer over networks, and there we can just require 0.6+ (or 1.0+ at some point)

**Comment by henryiii** [comment]
The real proposal is buried here, so let's open a new issue with just the proposal.
