### ISSUE TITLE
Duplicated storages

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#204]
This seems to have been washed into the discussion / PRs for storages, so just want to make sure it's addressed before release. 

Currently, we have two sets of storages, initialized and uninitialized. Reasons for removing the initialized storages:

```python
h = bh.histogram(bh.axis.regular(10,0,1), storage=bh.storage.Int)       # Fails
h = bh.histogram(bh.axis.regular(10,0,1), storage=bh.storage.Int())     # Works
h = bh.histogram(bh.axis.regular(10,0,1), storage=bh.storage.int)       # Works
h = bh.histogram(bh.axis.regular(10,0,1), storage=bh.storage.int())     # Fails
h = bh.histogram(bh.axis.regular(10,0,1), storage=bh.cpp.storage.int)   # Fails
h = bh.histogram(bh.axis.regular(10,0,1), storage=bh.cpp.storage.int()) # Works
```

* They make the interface harder to use correctly / easier to use incorrectly
* They violate "there should be only one way to do things" from the Zen
* They require users to know the meaning of capital first letter
    - Older stdlib and Numpy do not follow this naming scheme
    - Remember that PEP8 explicitly *allows* (does not require) a class that mostly acts like a function to be snake\_case, and storages explicitly have no interface, so even with PEP 8 there's some ambiguity
* They have different behavior based on capitalization, including `i<->I` (depends on the font)
* They will not scale well to configurable storages when those are added
* `from boost_histogram.storages import *` will override Python's `int()` (very minor issue)
* They are a deviation from Boost.Histogram, which does not provide preinitialized storages
* They conflict with storage class names in the cpp module, which have different usages
* They can be added later if users request them, they can't be removed easily

@HDembinski, no comment/discussion necessary, if you want to keep them just say no then close the issue. I'll go with whatever you say, and you won't hear about them again.

**Comment by HDembinski** [comment]
I am ok with removing the initialized storages.
