### ISSUE TITLE
cpp mode methods

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#207]
In `cpp` mode, I've been using methods instead of properties to exactly mimic C++. This will (still) cause a compromise somewhere: you can't set metadata without coming up with a new method or making it a property. Here are the options:

1. All argumentless methods are properties, like in Python mode. Note we also have `.at()`, which has an identical problem, but can't be made into a property.
2. `ax.metadata` is a property, all others are methods. 
3. `ax.metadata()` is a method, and `ax.metadata_set(value)` is available (name TBD), similar to `at/at_set` (name TBD). No methods are turned into properties.

I rather like number 3 best, I think, but no clear winner for me. @HDembinski ? Also, if there are any other things in C++ that support `x.y() =`, those would fall in this category with metadata.

**Comment by HDembinski** [comment]
Please go for number 2. We don't know yet, maybe some argument-less method will get an argument in the future, and then that would be breaking change if the method is a property in Python. For `.metadata` it is guaranteed that there won't be an additional argument.

**Comment by HDembinski** [comment]
Regarding `.at()`, I am very ok if this is simply not supported and setting only works via `__getitem__`

**Comment by henryiii** [comment]
Sounds good. Metadata is slightly special in Python, anyway, since it can store Python objects.

(Technically, there has to be an underlying method for the `__getitem__` to call, so there will always be one hidden away)

**Comment by HDembinski** [comment]
`.metadata` is also special in that it is the only thing that you can set on an axis after it was constructed
