### ISSUE TITLE
Copy method

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#209]
Many Python classes, like numpy's `array` and pandas' `DataFrame`, have a `.copy()` method. Besides being much easier to use interactively than the horribly named `import copy; copy.copy()` for a potentially very common operation, it also allows a configuration to be given. Numpy uses it to allow setting the order. Pandas just has a `deep=True` argument to allow deepcopy to be turned off (so it's just a shortcut). We could (possibly in the future) allow configuration here, like maybe selecting different axis types to copy to, or similar.

@HDembinski, what do you think? I've been meaning to suggest this since I tried to make a copy of a histogram for PyHEP.

**Comment by HDembinski** [comment]
I am not against it, if you think it is useful, we should have it.
