### ISSUE TITLE
h.view() for all storage types

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#21]

**Comment by HDembinski** [comment]
I will try to work on this next, now that I have a good feeling with the threaded support in boost::histogram.

**Comment by henryiii** [comment]
I don't think this will work; I'm pretty sure you cannot provide a view to a boost multi-precision int.

---

If that wasn't there, it would work, but would still be invalidated after filling if the type changed. So:

```python
v = np.asarray(h)
h.fill(0.5)
# Access to v is now ruined
v *= 0.5
# Access to v is now really ruined
```

(The nice thing is it can't shrink, so at least you won't get a segfault, I guess).

We can either drop the unlimited type, or disable these sorts of things and provide a copy method to get data. (The multi precision int will still be a problem)

**Comment by HDembinski** [comment]
The view of an unlimited_storage is always ruined, when you modify the type of the counters in C++. That either needs to be documented, or we always convert the internal counters to double when someone calls a view. I am for the second option.

**Comment by HDembinski** [comment]
I propose the following solution.
* We do not allow `np.asarray(hist)`, calling that will generate an error (how to implement this?). The only way to get a cell view is `hist.view()`.
* When the user calls `hist.view()` and the storage is `unlimited_storage`, we transform the internal types to `double`. Then we forward the view into the double buffer.

This avoids all problems with views becoming ruined.
* It is a safe solution for the user.
* It is simple to implement.
* It is consistent with the concept of unlimited_storage. To the outside world, it presents its cells as doubles. How it counts internally is supposed to be an implementation detail.
* People call `view()` after the histogram is filled to work with the cells, not in between. When they call it, it is e.g. to normalize the histogram. Practically all of these transformations need to convert the counters to double anyway.

**Comment by henryiii** [comment]
I was just thinking about turning off `np.asarray(hist)`; while we could allow it for simple storages, might be better to be consistent. Especially if we change the default to the unlimited storage.

**Comment by HDembinski** [comment]
1) I think we should keep it and rather document the issue with unlimited_storage. In normal usage, I cannot see how this is going to be a problem, because people fill first and then make an array view of the histogram after the filling to use the counters.

2) I am open to not have unlimited storage as the default. The question is whether we want to be memory conserving or fast by default. The unlimited_storage used to be faster in the past, but it got slower over time. I am not sure why. It may be possible to make it faster again, but that probably costs significant time.

**Comment by HDembinski** [comment]
Sorry, I should have read the full thread again before commenting. `np.asarray(hist)` calls `__array_interface__`. This can be implemented as a property, so it actually triggers a C++ function call. In this call we can trigger the conversion of the unlimited storage to double. This avoids all the problems with ruining the view, so it is safe. It would still require some documentation to make users aware that they should only do this after filling.

**Comment by HDembinski** [comment]
In the old python interface, I used a hybrid solution. If the unlimited storage was currently using a non-multiprecision type (which is basically always the case), `np.asarray(hist)` would return a view into this memory. Only if the internal counters were of the multiprecision type I would trigger the conversion to double I just mentioned.

We have to make a trade-off between the possibility to ruin the view and ruining the memory-conserving aspect of `unlimited_storage`

**Comment by henryiii** [comment]
Can we expand this to allow (or nicely disallow as needed?) view access on other types of storages? What would a view of a weighted storage ideally look like?

**Comment by HDembinski** [comment]
Good point. The accumulators do not necessarily have a binary structure that can be viewed in a useful way and changing the internal structure of the accumulators in such a way is unacceptable, as it severely limits the possible implementations (doing this may make accumulators slower and/or less accurate). A general solution would be to allocate a new numpy array when `.def_buffer` is called, and store the user-consumable result in there. As far as I know, this is allowed by the buffer interface. I like consistency and it

**Comment by HDembinski** [comment]
https://docs.scipy.org/doc/numpy/reference/arrays.interface.html
The `data` field can be another object which exposes the buffer interface, which includes a numpy array.

**Comment by henryiii** [comment]
This is important, but probably will miss the first beta.

**Comment by HDembinski** [comment]
I thought we have that already?

**Comment by douglasdavis** [comment]
Curious if this error:
```
Python 3.8.0 (default, Oct 17 2019, 21:37:23) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boost_histogram as bh
>>> h = bh.histogram(bh.axis.regular(10, -5, 5), storage=bh.storage.weight)
>>> h.view()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: NumPy type info missing for N5boost9histogram12accumulators12weighted_sumIdEE
```
is related to this issue?
(my boost-histogram installation is the 0.5.1 wheel)

**Comment by henryiii** [comment]
Yep, it is. We need(ed) to decide what accumulator histograms turn into when converted to an array. I think we have an idea now, one-way conversion to public values (they have extra internal values).

**Comment by henryiii** [comment]
You can access it by cell for the moment.

**Comment by henryiii** [comment]
Probably should have wrapped this with a nicer error message, at least...

**Comment by henryiii** [comment]
See also #175. One idea is that `.view` would return an accumulator storage proxy with `.values()`, etc. The buffer would just convert this to an array of values.

**Comment by HDembinski** [comment]
Makes sense.
