### ISSUE TITLE
Empty growable categories

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#215]
Currenty, we cannot make an empty growable category axis. The problem is that we can't know if an empty list is supposed to have strings or ints. Here are some ideas:

```python
bh.Category(str, growth=True)
bh.Category(int, growth=True)
```

Passing a type selects that type of axes but does not construct any str's or int's.

---

```python
bh.Category([], growth=str)
bh.Category([], growth=int)
```

Only growing axes have this issue, and str and int both ducktype as true anyway. Looks weirder than the first one.

---

```python
bh.Category([], dtype=str, growth=True)
bh.Category([], dtype=int, growth=True)
```

Nothing else has a dtype, but this does look rather normal.

---

```python
bh.Category[str]([], growth=True)
bh.Category[int]([], growth=True)
```

Let's be Cython, shall we?

---

```python
bh.StrCategory([], growth=True)
bh.IntCategory([], growth=True)
```

We give up on the single Category, and have two.

In any of these last ones, the `[]` could be optional.

@HDembinski ?

---

We need to make sure IntEnum is well supported, too; it might be nice to allow something like:

```python
class Cat(IntEnum):
    a = 1
    b = 3
bh.Category(Cat)
```

which is kind of in line with the first one. (Currently, `bh.Category(list(Cat))` works and that might be just fine, just something to think about).

**Comment by henryiii** [comment]
From #214

**Comment by henryiii** [comment]
I originally liked the first one because it's cute, now I think I like the last one best because it not cute (and simple, descriptive, and discoverable). We don't automatically select the type in any of the other Axis types (but they are all doubles). I'm not stuck on any one of them though.

**Comment by HDembinski** [comment]
I am leaning towards your first proposal:
```
bh.Category(str, growth=True)
bh.Category(int, growth=True)
```
It seems rather clear and easy to remember.

**Comment by HDembinski** [comment]
Agreed that IntEnum should also work.

**Comment by HDembinski** [comment]
Alternative: We could wrap a special category axis `bh::category<some_thing_derived_from_py_object>` for this case, which uses an immutable Python object as its value type, similar to sets and dicts. The category axis in C++ merely wants a type for which the equal operator is implemented. We already know how to wrap a Python object on the C++ side which is equal comparable, our `metadata_t` does just than.

**Comment by henryiii** [comment]
We have to call into Python to do the `==`, though. So this would be much slower. We don't fill against metadata, so it's not a performance penalty.

**Comment by henryiii** [comment]
(Unless you are thinking that the axis type can change once a value is encountered?)

**Comment by henryiii** [comment]
And, it might be worth measuring. Since users probably don't have numpy string arrays, we may be paying this price anyway for the conversion from python strings to numpy string arrays. Allowing any immutable Python object would be nice...

**Comment by HDembinski** [comment]
> We have to call into Python to do the `==`, though. So this would be much slower. We don't fill against metadata, so it's not a performance penalty.

When we fill whole arrays at once then yes, it would be much slower.

**Comment by HDembinski** [comment]
> And, it might be worth measuring. Since users probably don't have numpy string arrays, we may be paying this price anyway for the conversion from python strings to numpy string arrays. Allowing any immutable Python object would be nice...

Also true!

**Comment by henryiii** [comment]
So would you like option 1 for now, then work on a potential "all hashable objects" axis type for later?

**Comment by HDembinski** [comment]
I brought this alternative up, because it would allow us to avoid any of these surprising options and have a very simple category axis that's easy and straight-forward to use. I would not implement option 1 or any of the others if this works.

**Comment by HDembinski** [comment]
Thinking more about, I am also ok with `bh.StrCategory` and `bh.IntCategory`.

**Comment by HDembinski** [comment]
At least the `bh.IntCategory` should be much faster than the generic `bh.PyCategory`

**Comment by HDembinski** [comment]
Ok, I gave this more thought and convinced myself that we should use `bh.StrCategory` and `bh.IntCategory` as an intermediate solution, until we know how which strategy works best for a generic `bh.Category` that can accept Python objects.

What speaks for `bh.IntCategory`, etc.
* It is straight forward, language-wise, even beginners can understand that this is a specialized class. The initialization of `bh.IntCategory([], growth=True)` is unsurprising.
* We probably want to get rid of these explicit specializations in the long run. A class is easy to deprecate and the code is easy to migrate: just replace all instances of `IntCategory` with `Category`, etc.

In Python, it is always tempting to do something cute, because the language is so powerful and we have an urge to flex your programmer muscle, but it is important to resist temptation when designing interfaces. For interfaces, one should stay "boring" as much as possible, because "boring" means unsurprising and easy to understand even by beginners.

**Comment by henryiii** [comment]
Empty categories probably will have to wait till boostorg/histogram#252 is resolved, but the StrCategory/IntCategory can be changed.
