### ISSUE TITLE
Stale axes when growth=True and fill changes an axis

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#220]
Currently, the axes seem to be copies. They should not be.

**Comment by henryiii** [comment]
Example of problem:

```python
>>> h = bh.histogram(bh.axis.Integer(3,6, growth=True))

>>> h.axes[0]
Integer(3, 6, growth=True)

>>> h.fill(9)
histogram(
  Integer(3, 6, growth=True),
  storage=Double()) # Sum: 1.0

>>> h._axis(0)
Integer(3, 10, growth=True)

>>> h.axes[0]
Integer(3, 6, growth=True)
```

**Comment by HDembinski** [comment]
They should not be copies for consistency reasons and also because copying a variable axis or category axis is not super cheap.

**Comment by HDembinski** [comment]
Or any axis with a complex metadata. By the way, how can setting the metadata on an axis work if the axis is a copy??

**Comment by henryiii** [comment]
It doesn't.

```python
In [1]: h = bh.Histogram((10,0,1))

In [2]: h.axes[0].metadata = "hi"

In [3]: h
Out[3]:
Histogram(
  Regular(10, 0, 1, metadata='hi'),
  storage=Double())

In [4]: h[...]
Out[4]:
Histogram(
  Regular(10, 0, 1),
  storage=Double())
```

The caching mostly hides this, but it doesn't work currently.

**Comment by henryiii** [comment]
I believe I've removed one unneeded copy in a branch, but there's still one happening at the Pybind level; and if I remove that, it really likes segfaulting.

**Comment by henryiii** [comment]
I have a feeling the caching system does not interact well with copy and pickle. That needs to be checked (and very probably fixed).

**Comment by HDembinski** [comment]
Congrats on fixing this. This was a tricky one.
