### ISSUE TITLE
Remove test_basic_import.py

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#222]
Do we really need `test_basic_import.py`? What does an assert of a module do? It always passes, I would think. The name suggests that this test checks whether boost.histogram can be imported, but basically all other tests test this as well. I think this is not useful.

The other test checks whether the version info is the same in boost_histogram and  boost_histogram.version, which is automatically true since it is imported. So, all in all, I think this test can be removed.

**Comment by henryiii** [comment]
This was the very first test. There are quite a few areas the tests could be cleaned up.
