### ISSUE TITLE
Growable categories are not grown when adding histograms

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/boost-histogram#234]
Copy of part 6 of #214

When adding histograms, the growable categories are not as flexible as I'd like:
```
h = bh.histogram(bh.axis.category([''], growth=True), bh.axis.regular(20, 0, 1))
h2 = bh.histogram(bh.axis.category([''], growth=True), bh.axis.regular(20, 0, 1))
h.fill(np.array(['hi']), np.array([.1]))
h2.fill(np.array(['hi again']), np.array([.2]))
h + h2
```
raises `ValueError: axes of histograms differ`, when clearly one could be grown to accept the other
I tried a workaround:
```
h.fill(np.array(['hi', 'hi again']), np.array([0, 0]), weight=np.zeros(2))
h2.fill(np.array(['hi', 'hi again']), np.array([0, 0]), weight=np.zeros(2))
h + h2
```
which also fails since the categories are introduced in a different order in the respective histograms.

Comment from @HDembinski

> This is a very interesting point. You currently cannot add histograms which have different axes, therefore you get this error, but I see your point, probably this should actually work and do what you suggest, when the axes are growable. I need to think about it more, but I like your proposal.

**Comment by HDembinski** [comment]
Thanks for splitting this out. This seems like a nice feature to add.

**Comment by nsmith-** [comment]
Updated example for 0.7:
```python
import boost_histogram as bh
import numpy as np
h = bh.Histogram(bh.axis.StrCategory([''], growth=True), bh.axis.Regular(20, 0, 1))
h2 = bh.Histogram(bh.axis.StrCategory([''], growth=True), bh.axis.Regular(20, 0, 1))
h.fill(np.array(['hi']), np.array([.1]))
h2.fill(np.array(['hi again']), np.array([.2]))
h + h2
```
yes this is a surreptitious thread bump :)

**Comment by HDembinski** [comment]
Thanks for bumping, I haven't forgotten about this. Also see https://github.com/boostorg/histogram/issues/279 and https://github.com/boostorg/histogram/issues/251

**Comment by nsmith-** [comment]
Ok. I wonder, should I instead be looking towards a multihistogram/histbook concept instead of relying on growable string axes?

**Comment by HDembinski** [comment]
I started working on the patch in Boost.Histogram C++, but it is quite elaborate since I want to solve this generally and efficiently. It is going to happen, don't worry, but I cannot give an ETA. The workaround for now is to not use growing axes.

**Comment by HDembinski** [comment]
The feature is added in the boostorg/histogram develop branch now

**Comment by HDembinski** [comment]
(sorry, somehow hit close accidentally)

**Comment by henryiii** [comment]
That's fantastic. Will we need to implement something in boost-histogram or just update?

**Comment by HDembinski** [comment]
Hopefully, it is transparent to you, but I touched a lot of internals, to which boost-histogram is sensitive. If it does not work out of the box, it is because of those changes of internals.

**Comment by henryiii** [comment]
Okay, that's fine. Will update very soon, then!

**Comment by HDembinski** [comment]
The bug you reported is fixed on develop now.

**Comment by henryiii** [comment]
Should be fixed in boost-histogram too now. Closing, reopen if there's a problem!
