### ISSUE TITLE
Pickle performance

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#237]
Placeholder to investigate pickle performance.

**Comment by henryiii** [comment]
I expect we are making some unneeded copies, especially of things that could be no-copy numpy arrays.

Also, keep in mind, Pickle is famous for its horrible performance, and that's one of the two reasons it's not generally recommended for data storage. I bet we can improve our usage of it, but it may never be ideal.

* https://www.benfrederickson.com/dont-pickle-your-data/
* https://blog.hartleybrody.com/python-serialize/

**Comment by HDembinski** [comment]
I used to pickle the same histograms before, and the performance was ok.

**Comment by HDembinski** [comment]
Something changed some time after 0.5.x that made it slow.

**Comment by HDembinski** [comment]
You don't have to tell me about the pros and cons of pickling, I am very much aware of that. The article is pretty much opinionated bs, as pickle is on par with JSON, and you don't hear people screaming: don't use JSON. I use pickled histograms as caches, and for that purpose it works very nicely.

**Comment by HDembinski** [comment]
Lol, the article actually recommends JSON over pickles, even though JSON is a factor 2 slower for unpickling.

**Comment by HDembinski** [comment]
The only real good argument against pickles is the security risk, but I am willing to take that risk for my own analysis data. If someone can alter my pickles, then they can also alter my executable scripts.

Finally, if the performance problem is in the `__getstate__` method, then json or whatever else will be affected by the same slow-down.

**Comment by henryiii** [comment]
> Something changed some time after 0.5.x that made it slow.

This really should be fixable, then!

> article is pretty much opinionated bs

Just pointing out that pickles have a reputation for being slow, not that it's a great article. And it's becoming less true in more modern Python.

> even though JSON is a factor 2 slower for unpickling

(Totally unrelated to boost-histogram) I wonder how simdjson would do? One benefit of something as ubiquitous as JSON is the insane amount of work that goes into making it as fast as possible. Same is true for Javascript; if half of the money/research poured into JS was put into Python...

**Comment by HDembinski** [comment]
I found by accident that the problem lies in the pickling of storage.Weight(). storage.Double() is fast, but storage.Weight() takes forever.

**Comment by HDembinski** [comment]
Sorry about the strong reaction to the anti-pickle article, but I had this discussion before. I am happy to use knifes in the kitchen, even though knifes can cut people. Same with pickles.

**Comment by henryiii** [comment]
Pickling the storage as a record ndarray should be fast; can we override and trigger that somehow?

**Comment by henryiii** [comment]
And recently the accumulator objects gained buffer support, if that helps.

**Comment by HDembinski** [comment]
Yes that should help. The pickle code can be instructed to make use of that.

**Comment by HDembinski** [comment]
Ok, let's see, maybe I can do that today.
