### ISSUE TITLE
Text rendering of histogram

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#245]
I am missing the ASCII art histogram from boost::histogram, but I also like the current repr. In the console, it would be cool to do:
```
>>> my_hist.project(1) # project to some axis
Histogram(
  Regular(10, 0, 1),
  storage=Double())
# Sum: 0.0 (3.0 with flow)
# [0.0, 0.5)  1 ========
# [0.5, 1.0)  2 ==================
# [1.0, 1.5)  1 ========
```
Getting immediate feedback on a interactive projection would be very useful. On the other hand, if the axis has many bins, this could print a long wall of characters, which is annoying when you print a tuple of two histograms, which currently looks very nice (it is good when the repr is compact). I think therefore that the ASCII histogram shouldn't be drawn automatically. So what are the alternatives?

Brainstorming:
1) `repr(hist)` as is now, `str(hist)` generates ascii art for 1D
2) `bh.ascii_art = True` toggles the behaviour of `repr(hist)` globally.
3) `hist.print_project(1)` prints the art and that is pretty much all it does.
4) `hist.ascii()` generates the ascii art, so you can do `hist.project(1).ascii()`. But what should it return for N-dim?

**Comment by HDembinski** [comment]
Probably option 1 is the most pythonic. `str()` is supposed to return the user-friendly version, while `repr()` tries to be exact.

**Comment by henryiii** [comment]
A few thoughts:

1. `str(hist)` returns a string, and cannot take any options. It should not detect the terminal width and cannot be overridden explicitly with a terminal width. It also needs to be defined for ND histograms, so would look quite a bit different for N>1.
2. I'm not a fan of global toggles, though obviously they are used sometimes for this purpose (numpy), and I've implemented a few in the past. Repr has the same issue as str, plus the issue that it gets triggered very often.
3. This prints, rather than returning a string, so it can detect terminal width, but returning a string is more flexible, and it requires that you write "project" even if you have a 1D histogram. It does nicely force this to be 1D, though.
4. This is by far the most flexible, and it can have two keyword arguments; `out=sys.stdout` (which detects the width of the stream and prints), and `width=80`, which selects a width. Maybe a `truncate=1000` to limit long histograms someday, too? For now, it can give an error for 2D+ histograms, though we could eventually add a unicode 2D display.

I like the fourth one best. `str` could call `.ascii()` with some reasonable defaults.

**Comment by henryiii** [comment]
Keep in mind, string interpolation calls `str` by default, so writing:

```python
print(f"The histogram is {hist}")
```

Will call str.

**Comment by henryiii** [comment]
What do you think about having a truncate option actually rebin? That seems like a natural way to shorten a histogram. We'd just need a nice way to handle the final or first (or both) partial bins if the histogram did not divide nicely.

**Comment by henryiii** [comment]
Sneaky trick for now:

```python
In [3]: h._hist
Out[3]:
histogram(regular(10, 0, 1, metadata="None", options=underflow | overflow))
              +--------------------------------------------------------------+
[-inf,   0) 0 |                                                              |
[   0, 0.1) 0 |                                                              |
[ 0.1, 0.2) 0 |                                                              |
[ 0.2, 0.3) 0 |                                                              |
[ 0.3, 0.4) 0 |                                                              |
[ 0.4, 0.5) 0 |                                                              |
[ 0.5, 0.6) 0 |                                                              |
[ 0.6, 0.7) 0 |                                                              |
[ 0.7, 0.8) 0 |                                                              |
[ 0.8, 0.9) 0 |                                                              |
[ 0.9,   1) 0 |                                                              |
[   1, inf) 0 |                                                              |
              +--------------------------------------------------------------+
```

(Just noticed that)

**Comment by HDembinski** [comment]
Hah, good to know that one. :)

Good point regarding f-strings, that's probably not what we want to happen.

I don't like automatic rebinning. It is better than randomly skipping rows in the middle or elsewhere, but we really cannot predict what the user wants to see. I think printing the full 1D histogram is what you want most of the time, so that should be the default. I am leaning towards a special method to call the ascii art generation rather than using str()

**Comment by HDembinski** [comment]
Maybe the f-string issue is not so bad, you can instruct it to use repr instead with `!r`.

**Comment by henryiii** [comment]
You can, but I was just pointing out the default.

It's not unusual, especially with the easy rebinning, to have 100s or 1000s of bins in a 1D histogram, and a 1K line printout is unmanageable on the shell, and is not useful (you can't get a an idea of what the histogram looks like from 1K lines). It's especially bad if you can trigger such a massive printout accidentally from a common method.

I think having print show a single-page representation of a histogram (roughly 10-20 bins max), and `.ascii()` having a configurable view with no default limit would be a good mix.

**Comment by HDembinski** [comment]
> It's not unusual, especially with the easy rebinning, to have 100s or 1000s of bins in a 1D histogram, and a 1K line printout is unmanageable on the shell, and is not useful (you can't get a an idea of what the histogram looks like from 1K lines). It's especially bad if you can trigger such a massive printout accidentally from a common method.

Then you simply have to manually rebin before calling `str()`. Again, we cannot predict what the user wants and we cannot configure what `str()` does. So you cannot simply assume that the user wants to see less.

**Comment by HDembinski** [comment]
Also, my histograms do not have 100 or 1000s of bins. Take it from someone who actually uses histograms in practice.

**Comment by HDembinski** [comment]
I hear your arguments, but I am not convinced. Get a long printout by accident is not the end of the world.

**Comment by HDembinski** [comment]
I am convinced that `str()` is the best option. If you want to configure what is going to be printed, you transform the histogram beforehand. `str(h.project(1).reduce(bh.algorithm.rebin(2)))`.

**Comment by henryiii** [comment]
You still can't configure the width of the printout if you don't also have a method. I'm fine with it being in the `str`, but I'd like to have a configurable method that produces just that part (and not the little header at the top, that's from `__repr__` - so str would be `repr()` + `.ascii()`). It doesn't have to have a limit/rebin option, though the type of rebinning I was thinking of would not be possible as a normal rebin.

> my histograms do not have 100 or 1000s of bins. Take it from someone who actually uses histograms in practice.

We don't have to have a method to shrink the display. But you assume anyone using larger numbers of bins is wrong? And all users of histograms inside and outside of HEP will be just like you? I've used up to 600 bins quite regularly. I think 50 is the smallest number I've regularly used. It really depends on what you are doing And, since rebinning is so easy, taking a multiple of your favorite binnings and then rebinning down may be a common way to work (I did that all the time on expensive histograms).

Also, adding a limit only affects people who go *over* the limit.


By the way, this is a mockup of what I was thinking:

```
histogram(regular(100, 0, 1, metadata="None", options=underflow | overflow))
              +--------------------------------------------------------------+
[-inf,   0) 0 |                                                              | (1 bin)
[   0, 0.1) 0 |                                                              | (10 bins)
[ 0.1, 0.2) 0 |                                                              | (10 bins)
[ 0.2, 0.3) 0 |                                                              | (10 bins)
[ 0.3, 0.4) 0 |                                                              | (10 bins)
[ 0.4, 0.5) 0 |                                                              | (10 bins)
[ 0.5, 0.6) 0 |                                                              | (10 bins)
[ 0.6, 0.7) 0 |                                                              | (10 bins)
[ 0.7, 0.8) 0 |                                                              | (10 bins)
[ 0.8, 0.9) 0 |                                                              | (10 bins)
[ 0.9,   1) 0 |                                                              | (10 bins)
[   1, inf) 0 |                                                              | (1 bin)
              +--------------------------------------------------------------+
```

Bin edges would always be exact; total number of bins on the edges might be less so this might be "variable"-like even if it was a regular binning.

**Comment by henryiii** [comment]
Do we really want ascii? Unicode could allow a much nicer display, and is generally always available in Python. We could have an ascii fallback.

**Comment by henryiii** [comment]
Quick mockup in unicode:

```
histogram(regular(100, 0, 1, metadata="None", options=underflow │ overflow))
              ╭──────────────────────────────────────────────────────────────╮
[─inf,   0) 4 │▋                                                             │ (1 bin)
[   0, 0.1) 30│███                                                           │ (10 bins)
[ 0.1, 0.2) 52│████▉▏                                                        │ (10 bins)
[ 0.2, 0.3) 65│██████▋                                                       │ (10 bins)
[ 0.3, 0.4) 30│███                                                           │ (10 bins)
[ 0.4, 0.5) 6 │█                                                             │ (10 bins)
[ 0.5, 0.6) 3 │▍                                                             │ (10 bins)
[ 0.6, 0.7) 2 │▍                                                             │ (10 bins)
[ 0.7, 0.8) 1 │▏                                                             │ (10 bins)
[ 0.8, 0.9) 1 │▏                                                             │ (10 bins)
[ 0.9,   1) 0 │                                                              │ (10 bins)
[   1, inf) 0 │                                                              │ (1 bin)
              ╰──────────────────────────────────────────────────────────────╯
```

**Comment by henryiii** [comment]
And, a mockup for 2D:

```
              ╭───────────────────────────────────────────────────────╮
              │                                                       │
              │             ░░░░░░░░░░░░░░░░░░░░░░░░░░                │
              │         ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░            │
              │         ░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░            │
              │         ░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░            │
              │         ░░░░▒▒▒▒▒▒▒▒▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒░░░░░░░            │
              │        ░░░░░▒▒▒▒▒▒▒▒▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒░░░░░░░░           │
              │       ░░░░░░▒▒▒▒▒▒▒▓▓████▓▓▓▒▒▒▒▒▒▒▒░░░░░░░░          │
              │       ░░░░░░▒▒▒▒▒▒▒▓▓████▓▓▓▒▒▒▒▒▒▒▒░░░░░░░░          │
              │        ░░░░░▒▒▒▒▒▒▒▒▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒░░░░░░░░           │
              │         ░░░░▒▒▒▒▒▒▒▒▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒░░░░░░░            │
              │         ░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░            │
              │         ░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░            │
              │         ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░            │
              │             ░░░░░░░░░░░░░░░░░░░░░░░░░░                │
              │                                                       │
              │                                                       │
              ╰───────────────────────────────────────────────────────╯
```

**Comment by HDembinski** [comment]
Those are great. Sure, if we can make even nicer displays, we should go for that. We don't have to be backward compatible in what `str()` returns.

The fact that we probably want to switch to unicode displays as some point makes the name `.ascii` even more unappealing. What about `.show()` or `.display()`?

**Comment by HDembinski** [comment]
I would still make `str()` call `.show()` or `.display()`. Showing a histogram that's silently rebinned is confusing.

**Comment by henryiii** [comment]
I like both names, maybe `show` is slightly better? I didn't like `.ascii` for that reason. ;) And yes, `str()` would call `.show()` with appropriate defaults. And with ascii mode turned on for Python 2 (`unicode()` would be required to get the unicode display in Python 2.).

> Showing a histogram that's silently rebinned is confusing.

It doesn't help to have the number of bins being combined in the display? No plotting software (that I've seen) plots a histogram wider than your screen when you increase the number of bins, they always shrink to the display size (by making narrow bins). We are limited by lines, so can't shrink without showing multiple bins in one line.

`.show()` could give you explicit control, of course.

**Comment by HDembinski** [comment]
We should definitely adjust the width to the terminal width, but I would like the full length printed by default. I had this situation just yesterday where I needed to debug my analysis and being able to see the whole histogram was really useful. This is the lowest layer. Libraries on top of boost-histogram like hist can change the printing.

**Comment by HDembinski** [comment]
I think we settled for a solution, so I am starting a PR now.

**Comment by HDembinski** [comment]
Hm, I think this needs some more discussion, but better to do that in the PR.

**Comment by henryiii** [comment]
We should either close this or reassign it to 0.7.0.

**Comment by henryiii** [comment]
The solution we have is okay, and we can always revisit.
