### ISSUE TITLE
Rename *Int -> *Int64

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#248]
In the future, we might want to add more integer options, so I'd like to suggest future-proofing by renaming:

* `Int` -> `Int64` (depending on the result of #241)
* `AtomicInt` -> `AtomicInt64`

Even if we never add different bit lengths, this still clearly communicates the storage capabilities, just like `Double` clearly indicates that this is a 64 bit float.

**Comment by henryiii** [comment]
(Marked as 0.6 because we need to decide and make this change before 0.6 to minimize renames later)

**Comment by HDembinski** [comment]
That's fine, but I want to remove the int storage.

**Comment by HDembinski** [comment]
The other nice thing about this is that we can drop the annoying `_` in C++. `int64` is not reserved.
