### ISSUE TITLE
new `.reduce` interface 

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#252]
```
    h = bh.Histogram(bh.axis.Regular(20, 1, 5))
    h.fill(1.1)
    hs = h.reduce(bh.algorithm.rebin(0, 4))
    assert_array_equal(hs.view(), [1, 0, 0, 0, 0])
```
`rebin` should not live in algorithm, this makes no sense now since all the algorithms are methods. It still makes sense for the cpp skin. So `bh.cpp.algorithm.rebin` is ok, but for the main Python skin, it should be `bh.tags.rebin(0, 4)`. For a 1D histogram, you should be able to use `bh.tags.rebin(4)` just like in C++. Similar for `shrink` and `shrink_and_rebin`.

**Comment by HDembinski** [comment]
Also, the documentation of `.reduce` does not tell users how to use it.

**Comment by henryiii** [comment]
This is better than algorithm, but then it mixes what you can use in indexing with these, which only work in reduce. What about `bh.reduce.rebin`, etc? Then it's clear what your options for reduce are, and what your options for indexing are.

Documentation is a bit lacking in a few areas, working on that!

**Comment by henryiii** [comment]
Note: It's `bh.tag`, not `bh.tags`. Only `accumulators` is plural, all other modules are singular.

**Comment by HDembinski** [comment]
You are mixing a few arguments here. `bh.cpp.algorithm.sum` is a function algorithm, not a tag. And yes, I don't tags and functions to be mixed, they are conceptually different. `bh.cpp.algorithm.rebin` is a tag and `bh.tag.rebin` is a tag. So these should be merged if possible. I think the problem is that they do not have the same syntax. `rebin()` for `.reduce` accepts a number or two, while I think the `rebin` for UHI accepts only one number.

`bh.reducers.rebin` is better, but having two separate tags is silly from the users point of view. I would prefer to get rid of the tags for `.reduce` completely. In fact, if UHI works, I don't want to have `.reduce` at all in the Pythonic interface.

**Comment by HDembinski** [comment]
All of this does not apply to `bh.cpp`, of course.

**Comment by HDembinski** [comment]
I think it is very very awkward to have to different sets of tag types in the Pythonic interface , with same names, but slightly different semantics which need to be imported from different places. This is absolute no-go. So we have several options.

1) remove `.reduce`, since the functionality is provided by the UHI.
2) change the call syntax for `.reduce` to not use tags

I am tending towards the second option. Syntax looks like this:
```
h1d.reduce(1.2, 3.4) # shrinks axis 0
h1d.reduce(1.2, 3.4, 2) # shrinks axis 0 and rebins

# the key is the axis index, shrink axis 0 and shrink and rebin axis 1
h2d.reduce({0: (1.2, 3.4), 1: (4.2, 6.5, 2)}) 
```

**Comment by HDembinski** [comment]
If you want to keep `.reduce` to use it internally as a backend for the UHI, then it should be a private method `._reduce`.

**Comment by henryiii** [comment]
I like the second option. I don't think we should have a 1D version; the one and only argument is a dictionary of axes to apply on. 

I think it probably should offer `slice_and_rebin`, rather than `shrink_and_rebin`, because you can convert from data space to bin space more easily than the other way around:

```python
h2d.reduce({0: (1, 5), 1: (4, 8, 2)})
```

And, it could even UHI locators, since it's a Python interface:

```python
h2d.reduce({0: (bh.loc(1.2), bh.loc(3.4)), 1: (bh.loc(4.2), bh.loc(6.5), 2)}) 
```

Remember, the goal is to fix the one deficiency of UHI: it's hard to select 1 or a small number of axes by number from a large collection of them and just modify those. If you have 1 axis, UHI is completely sufficient. Downstream libraries like Coffea can then build this dictionaries however they currently do it.

**Comment by HDembinski** [comment]
Ok, a solution that allows to use indices and values is even better and it uses the `bh.tag`s. Nice that we can agree on something every now and then. 
Although I want my specialized version for 1D. There is no reason to not have it.

**Comment by HDembinski** [comment]
So just to clarify, the following should work:
```
h.reduce({0: 2}) # rebins
h.reduce({0: (1, 3)}) # slices
h.reduce({0: (1, 3, 2}) # slides and rebins
```
Indices can be replaced with `bh.tag.loc` to use values instead.

**Comment by henryiii** [comment]
There are two reasons:

* This duplicates UHI, providing two ways to do this
* Having two signatures is not pythonic; there's no way to do it without manually working behind the scenes to make it work, unlike in C++. Look at what the signature would have to be:

```python
def reduce(self, reduce_dict_or_lower_edge, upper_edge=None, rebin=None):
```

Not the end of the world, but not very clear for a shortcut that is already completely available in the `[]` form.

**Comment by HDembinski** [comment]
You also introduced shorthand for the regular axis.

**Comment by henryiii** [comment]
And not type safe:

```python
def reduce(self, reduce_dict_or_lower_edge : Union[dict, int], upper_edge: Optional[int] =None, rebin : Optional[int] =None):
```

You can't indicate that it's an error to put a dict in 1 and an int in 2.

**Comment by HDembinski** [comment]
I see the point of the signature, but it does not become easier with what you suggest:
`def reduce(self, reduct_dict)` is equally cryptic.

**Comment by HDembinski** [comment]
Look, I don't see why I should not add a shorthand here, when you add short hands elsewhere.

**Comment by HDembinski** [comment]
We can also remove the regular axis shorthand, then I am ok with this here.

**Comment by henryiii** [comment]
You can explain what the reduce dict is; it's not that it's cryptic, but that it takes two things.


Again, not the end of the world, but not needed since we can just use UHI for the shortcut form and this is targeted solely at making reducing by axis number simpler.

> You also introduced shorthand for the regular axis.

And I've avoided advertising it, and am ready to remove it if needed, but it's very quick and easy and is not simply available elsewhere. You can't make a histogram with so few characters otherwise. And it is simpler than this one; you can give a `Union(tuple, Axis)` and it mixes just fine with multiple axis, you can mix and match. You can't mix and match this shortcut.

**Comment by henryiii** [comment]
I use the regular axis shorthand dozens of times per day, so I'd prefer not to remove it until we are done with development, but it's not mentioned (anymore) in any documentation and is not publicized (except by accident).

**Comment by HDembinski** [comment]
Ok, then let's remove the shorthand for regular and have no shorthand here. Deal. I prefer to have less shorthands in the bottom layer that is boost.histogram. I never missed the shorthand, I actually like typing out the name of the axis in my code, because that it is super clear what is going on.

**Comment by henryiii** [comment]
I'm happy to add a warning saying this is a developer feature than may be removed.

**Comment by HDembinski** [comment]
hist can and probably should have all kinds of nice shorthands.

**Comment by henryiii** [comment]
Yes, and I have some ideas for that. ;)

**Comment by HDembinski** [comment]
Do you want to implement this or should I?

**Comment by henryiii** [comment]
I can do it if you'd like, I have a few minutes.

**Comment by HDembinski** [comment]
Ok, please go ahead. I already did my days work with fixing the pickling. ;)

**Comment by henryiii** [comment]
I'll add the developer shortcut warning for the Regular shortcut in the same PR. We are almost at the point that such rapid development is over and it can be removed, so if you really want it removed now instead of in 0.7.0, I think I could manage.

**Comment by henryiii** [comment]
Note to self: also fix the cpp missing shortcut while I'm at it...

**Comment by HDembinski** [comment]
If you want, you can leave the cpp skin to me, since I am the one who mostly cares about that part.

**Comment by henryiii** [comment]
@HDembinski @jpivarski I just realized, while in the Xarray tutorial at SciPy, this "dict in index" syntax is exactly what is used in Xarray, too! :)
