### ISSUE TITLE
1D shorthands for rebin and shrink etc are not implemented

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#253]
C++ has are shorthands for `rebin`, `shrink`, etc, when there is only one axis. Instead of typing `rebin(0, 2)` you can just type `rebin(2)`. This is currently not supported.

**Comment by henryiii** [comment]
This is not a bug, just a missing feature. We should get it in, though.

We need to make sure that:

```python
h = # 2d hist
h.reduce(rebin(2), rebin(3))
```

produces a nice error.

**Comment by henryiii** [comment]
Also (I think this is why I didn't add it originally), how would you do the shortcut, mimic a C++ style overload, where one behavior for 1 argument and a different behavior for argument 1 if there are two arguments? That is done in a few places in Python (like `range`). Or would you recommend a keyword argument, so `rebin(2, axis=1)`?

**Comment by henryiii** [comment]
Also keep in mind that these do not provide an advantage over UHI for 1D histograms, but only ND (I believe, anyway), so users really should use UHI instead of the shortcut form.

**Comment by HDembinski** [comment]
I call this a bug, because it is not a proper reflection of the C++ interface.

These are all good points, but all the more reason to get rid of `.reduce` in the Python skin. The cpp skin still needs this functionality, though. For the rebin tag, you can add two inits to the `py::class_`, one with one argument, and one with two arguments.

```h.reduce(rebin(2), rebin(3))```

triggers an exception in C++.

**Comment by HDembinski** [comment]
Closing this as #252 is converging on a different solution.
