### ISSUE TITLE
Allow adding constants

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#261]
Consider the following code (from my analysis), which sums up histograms generated in different threads:
```
h_tot = None
for h in generate_histograms():
  if h_tot is None:
    h_tot = h
  else:
    h_tot += h
```
It would be nicer to be able to write it like this (or something similar)
```
h_tot = 0
for h in generate_histograms():
   h_tot = h_tot + h
```
We currently don't allow adding numbers to histograms. So to get this feature, we should allow this. Adding a number to a histogram would only be allowed if that is supported by the underlying accumulator.

**Comment by henryiii** [comment]
This is useful, though you should be able to do (assuming this is all you are doing):

```python
import functools, operator

h_tot = functools.reduce(operator.add, generate_histograms())
```

Allowing scalar addition *might* even enable:

```python
h_tot = sum(generate_histograms())
```

**Comment by HDembinski** [comment]
You are right, I could write it in more clever ways, but it is also nice to support the naive way (but I think we agree on that).

**Comment by HDembinski** [comment]
Note that adding may trigger a storage conversion:
```
bh.Histogram(bh.axis.Integer(0, 3), storage=bh.storage.Int64()) + 0.5
```
This should convert the Histogram storage to `Double()` for symmetry with numpy arrays.

Boost.Histogram when you add two histograms with different storage, the C++ code selects the common type for the result. So int + double yields double, for instance.

**Comment by HDembinski** [comment]
The same thing happens when you scale.

**Comment by HDembinski** [comment]
Turns out the Python code currently does not support add histograms with different storages.
```
h = bhc.histogram(bhc.axis.regular(10, 0, 1), storage=bhc.storage.int64())
h2 = bhc.histogram(bhc.axis.regular(10, 0, 1), storage=bhc.storage.double())

In [19]: h + h2
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-360da8eb62ae> in <module>
----> 1 h + h2

~/Code/boost-histogram/boost_histogram/_internal/hist.py in __add__(self, other)
    127
    128     def __add__(self, other):
--> 129         return self.__class__(self._hist + other._hist)
    130
    131     def __eq__(self, other):

TypeError: unsupported operand type(s) for +: 'boost_histogram._core.hist.any_int64' and 'boost_histogram._core.hist.any_double'
```

**Comment by LovelyBuggies** [comment]
I think this issue (adding const & fix add func) could be solved with #289 , as they are all related to storage type. Besides, I think this snippet should work, but currently NOT.

```python
>>> h = bh.Histogram(bh.axis.Regular(10, 0, 1), storage=bh.storage.Int64())
>>> h2 = bh.Histogram(bh.axis.Regular(10, 0, 1), storage=bh.storage.Double())
>>> assert h==h2
```

It looks like maybe `__eq__` also need to be renewed.

**Comment by henryiii** [comment]
@HDembinski, is `h += 1.0;` not supported in Boost.Histogram? This doesn't seem to work in c++:

```cpp  
  std::vector<double> v = {1.0, 2.0, 3.0, 4.0, 5.0};
  auto h = bh::make_histogram(bh::axis::variable<>(v));
  h += 1.0;
```

Should it be? Or should the be Python only?

**Comment by henryiii** [comment]
And what does `h += 1` do to the flow bins? Should this really just be a special case for 0, to enable the trick above?

**Comment by HDembinski** [comment]
It is not supported currently, because the operation seemed to make little sense for a real histogram. But it can easily be added.

**Comment by henryiii** [comment]
I'm thinking it is probably best in Python to allow False-like (0, 0.0, None, False) to do nothing when added to a histogram, and disallow adding non-False values, since they are ambiguous. For a real histogram, I don't think adding a constant to all bins that makes physical sense, especially if bins are not equal size.
