### ISSUE TITLE
view of weight storage is broken

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#277]
I have a filled multi-dimensional histogram with a weight storage. I find that the arrays returned by `.value` and `.variance` are the same while they shouldn't be.
```
h = bh.Histogram(..., storage=bh.storage.Weight())
v = h.view()
assert np.any(v["value"] != v["variance"]) # OK
assert np.any(v.value != v.variance) # ERROR
```
I will try to make a minimal example.

**Comment by henryiii** [comment]
This was discovered and fixed in #273.

**Comment by henryiii** [comment]
It's a very bad bug, so I'd like to get a 0.6.1 out soon with the fix.

**Comment by HDembinski** [comment]
I am closing this, the fix looks ok and it has tests.
