### ISSUE TITLE
PR Check Unsuccessful

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/boost-histogram#308]
I pulled a request [#307](https://github.com/scikit-hep/boost-histogram/pull/307) to fix some bugs in the example codes and document. But git shows that the check is unsuccessful, plz help me with this problem! 

```
Run actions/setup-python@v11s
3.8.1 (x64)
Run actions/setup-python@v1
##[error]Version 3.8.0 with arch x64 not found
Available versions:

2.7.17 (x64)
3.5.9 (x64)
3.6.10 (x64)
3.7.6 (x64)
3.8.1 (x64)
```

**Comment by henryiii** [comment]
Looks like a minor bug in the CI. I think it needs 3.8.1 instead of 3.8.0 (they have just deleted that one, perhaps?). We should be able to just ask for 3.8 and not worry about the patch version.
