### ISSUE TITLE
Where is _core

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/boost-histogram#318]
In `./boost-histogram/boost_histogram/_internal/axis.py`, we import packages like this.

```python
from __future__ import absolute_import, division, print_function

del absolute_import, division, print_function

from .._core.axis import options

from .._core import axis as ca

from .kwargs import KWArgs
from .sig_tools import inject_signature
from .axis_transform import AxisTransform
from .utils import cast, register, set_family, MAIN_FAMILY, CPP_FAMILY, set_module

import warnings
import copy
```

But for the 5th and 7th lines, I did not find the `_core` folder in `boost_histogram`, so where is it?

**Comment by henryiii** [comment]
`_core` is the C++ part, and it gets built out of the files in `src/**.cpp`. It is a [PyBind11](https://pybind11.readthedocs.io/en/stable/) binding to the C++14 Boost library "Histogram". It is only there when you build via CMake or Pip (and it sits in the site packages install, in general).

**Comment by LovelyBuggies** [comment]
Got it!

**Comment by LovelyBuggies** [comment]
Uh... seems like `_core.cpython-37m-darwin.so` is an executable file generated by those `.cpp` files. No use to find source codes here, just see `src/*.cpp` files.
