### ISSUE TITLE
Support for static histograms

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#32]
Static tuples of axes could be supported except for `project`.

**Comment by HDembinski** [comment]
Again, I think this is not giving you a speed advantage, that's what my benchmarks in C++ suggest.

**Comment by HDembinski** [comment]
You don't need to use the full C++ API.

**Comment by henryiii** [comment]
It would be nice to have this (long term, not short term) so a user could build an extension with a custom collection of non-identical axes and bind it. Static axes would not be part of the core library.

**Comment by HDembinski** [comment]
How would that work from Python? We could allow users to implement an axis in Python and use it with boost-histogram. That's totally doable. But how would you allow people to use static tuples of axes, this requires recompilation?

**Comment by henryiii** [comment]
They would compile an extension. It's not for the faint of heart, but it might be possible to simply call the headers and make an extension that doesn't require recompiling the rest of the boost-histogram library (say for experiments). This is not a well thought out plan, just an idea based on the discussion there.

**Comment by henryiii** [comment]
I'm also interested in adding Python functions for transforms in the long run.

**Comment by HDembinski** [comment]
Yeah, that would be cool.
