### ISSUE TITLE
Do we follow a PEP 8 python style ? 

### ISSUE THREAD

**Issue by ChanchalKumarMaji** [scikit-hep/boost-histogram#322]
@henryiii Do we follow the rules of [PEP 8](https://www.python.org/dev/peps/pep-0008/) in this repository ? I see some places where `PEP 8` has not been followed in this repository. Thank You !

**Comment by henryiii** [comment]
The code is formatted with black. Naming is mostly PEP 8 compliant, maybe not in the `cpp` module. Can you point out places where it is not PEP 8 compliant? I don't have a test for that other than black.

**Comment by ChanchalKumarMaji** [comment]
I have modified the docs where some spaces were missing. Thank You.
