### ISSUE TITLE
Doc for notebooks

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/boost-histogram#326]
We can convert ".ipynb" files directly to sphinx docs by using [nbsphinx](https://nbsphinx.readthedocs.io/en/0.5.1/index.html), instead of exporting them as ".rst" files on Jupyter and then add to doc "./doc/source" (*looks like the ".rst" files in folder "[./doc/source/usage"](https://github.com/scikit-hep/boost-histogram/tree/develop/docs/usage) are created in this way*). This method is more flexible, convenient, and pretty easy to implement, just to add extensions and exclude patters to ["conf.py"](https://github.com/scikit-hep/boost-histogram/blob/develop/docs/conf.py) is ok.

**Comment by henryiii** [comment]
The docs are not from notebooks (though often the code in the docs is tested in a notebook), but it would be nice to put the example notebooks in the docs as well!
