### ISSUE TITLE
bh.sum problem

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/boost-histogram#337]
@henryiii Henry, I found a potential problem in boost-hist's new `__get_item__()` method. When we use `valid_only = h[{2:bh.loc(1)}]` in a 3D-histogram, what do we expect to get? A new 3-D histogram or a 2-D histogram. I think the former is preferable. I found the dimensionality is reduced. You can see the details in my **passed** tests [here](https://github.com/LovelyBuggies/Nino-hist/blob/master/tests/test_bool.py).

**Comment by henryiii** [comment]
You should get a reduced histogram. It behaves exactly like Numpy: Selecting a single value reduces the dimensionality. Making a slice (`valid_only = h[{2:slice(bh.loc(1), bh.loc(1)+1)`) does not. Maybe easier to see with `h[:, :, bh.loc(1)]` and `h[:, :, bh.loc(1) + 1]`.

**Comment by LovelyBuggies** [comment]
Ok, that's good. I just thought it was reasonable :)

**Comment by LovelyBuggies** [comment]
But

**Comment by LovelyBuggies** [comment]
If so, `valid_and_invalid = h[{'V':slice(None, None, bh.sum)}]` should also reduce the dimensionality, shouldn't it? This will generate a 3-D histogram (only one bin in the last dimension) when I am testing: `assert h[0,0,0]` passed, `assert h[0,0]` failed.

**Comment by LovelyBuggies** [comment]
Btw, should we support for `valid_and_invalid = h[{'V':bh.sum}]`?

**Comment by henryiii** [comment]
Yes, `h[{2:slice(None, None, bh.sum)}].rank` should be 2, not 3. Can you check rank?

`h[{'V':bh.sum}]` would only be Hist; you mean `h[{2:bh.sum}]`, and for now, no, not in boost-histogram. We can try to support this sort of a shortcut in Hist, and propose it for boost-histogram if it ends up working and not interfering with UHI in some unexpected way.

**Comment by LovelyBuggies** [comment]
😳Sorryyyy ... I mistaked the new hist `valid_and_invalid` as the old `h`. NO problem exists!

**Comment by LovelyBuggies** [comment]
> `h[{'V':bh.sum}]` would only be Hist; you mean `h[{2:bh.sum}]`, and for now, no, not in boost-histogram. We can try to support this sort of a shortcut in Hist, and propose it for boost-histogram if it ends up working and not interfering with UHI in some unexpected way.

Yes!

**Comment by henryiii** [comment]
This seems to be working correctly:

```python
import boost_histogram as bh
h = bh.Histogram((10,1,10), (5, -2, 2), (2, 0, 1)) # (Note, this is a developer shortcut and will be removed in the future)
h2 = h[{2:slice(None, None, bh.sum)}]
```

`h2` looks like this:

```
Histogram(
  Regular(10, 1, 10),
  Regular(5, -2, 2),
  storage=Double())
```

And `.shape` is `(10, 5)`, `.rank` is `2`.

**Comment by henryiii** [comment]
> NO problem exists!!

Oh, sorry, I see you found this, never mind.

**Comment by LovelyBuggies** [comment]
Yep, I found it. While another ToDo item still exists, I change the issue name. And you might need to reconsider this point.

> you mean h[{2:bh.sum}], and for now, no, not in boost-histogram. We can try to support this sort of a shortcut in Hist, and propose it for boost-histogram if it ends up working and not interfering with UHI in some unexpected way.
