### ISSUE TITLE
Cloudpickle fails on boost-histogram

### ISSUE THREAD

**Issue by paulgessinger** [scikit-hep/boost-histogram#342]
I'm using boost histograms inside Coffea accumulators. I ran into the issue now that boost histograms appear not to be pickleable by cloudpickle (anymore? I think this used to work). 

When running something like this:

```python
import cloudpickle
h = bh.Histogram(bh.axis.Regular(50, 0, 20))
h.fill([1 ,2 , 3, 4, 5])
cloudpickle.dumps(h)
```

I get an error like

```
AttributeError: module 'boost_histogram._core' has no attribute '__path__'
```

Should that even work? If so, any pointers how I can resolve or circumvent this issue? This is especially unfortunate since standard pickle appears to work fine, but Coffea uses cloudpickle.

**Comment by henryiii** [comment]
This should be doable, as long as you can cloudpickle numpy arrays and things like that. I thought cloudpickle was supposed to simply pickle any normally picklable objects. I'll check, and maybe see if I can add it to the tests.

**Comment by paulgessinger** [comment]
I **think** it's failing **while** trying to figure out if the module is a dynamic one or not, where cloudpickle advertises being able to also serialize dynamic ones.

**Comment by henryiii** [comment]
Can you try the following workaround:

```python
bh._core.hist.__file__ = bh._core.__file__
```

?

**Comment by paulgessinger** [comment]
The workaround does fix it it for me! Thanks for the help!
