### ISSUE TITLE
pip editable fails

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/boost-histogram#344]
I got an error when I pip install in virtual environment.

```bash
(.env)$ pip install -e -v .[all]
ERROR: -v is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).
```

Not sure why this happens. Don't we need to `pip install -r dev-requirements.txt`?

**Comment by LovelyBuggies** [comment]
Why not remove `-r`, by doing this everything becomes good.

**Comment by henryiii** [comment]
The `-e` is special for pip, it must proceed `.`. So reordering should work: `pip install -v -e .[all] `.

Let me know if it's incorrect in docs somewhere!

**Comment by henryiii** [comment]
The package was restructured, you may have to clean your directory if you built with an old version inplace, then updated. (delete the .egg file).

**Comment by LovelyBuggies** [comment]
> Let me know if it's incorrect in docs somewhere!

In CONTRIBUTING.md (*2). Search `pip install -e -v .`.
