### ISSUE TITLE
Allow axis transform

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/boost-histogram#347]
https://github.com/scikit-hep/boost-histogram/blob/8848dae3cb487d4661270134cdde66b16ad75e26/tests/test_axis.py#L140-L142

We should allow the axes to be transformed in 0.8.0, instead of only the Histogram instance.

**Comment by henryiii** [comment]
We do, this just is checking for a missing argument to Pow. `bh.axis.Regular(1, 1.0, 2.0, transform=bh.axis.transform.Pow(2))` is valid.

**Comment by LovelyBuggies** [comment]
> We do, this just is checking for a missing argument to Pow.

Is `bh.axis.Regular(1, 1.0, 2.0, transform=bh.axis.transform.Pow) ` now supported?

**Comment by henryiii** [comment]
The `(2)` is required, but otherwise, this is always applied to an axis.
