### ISSUE TITLE
Allow implicit conversion of Python sequence to WeightedSum

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#356]
I recently found the need to set the weighted sum manually in a histogram with `storage.Weight`.
```
h[1, 2] = bh.accumulators.WeightedSum(1, 2) # ok
h[1, 2] = (1, 2) # fails
```
In pybind11, one can declare implicit conversions. So I think technically we could easily allow the second line to work. It is less explicit than the first, but rather practical. I don't think we should allow such conversions for all accumulator types, but for WeightedSum at least it seems safe.

**Comment by henryiii** [comment]
What should this do for ranges? That is,

```python
h[1:5] = ((1,2,3,4), (1,2,3,4))
```

I think this is fine? This would be useful, for example, for converting from uproot:

```python
h[:] = (uphist.allbins, uphist.allvariances)
```

**Comment by HDembinski** [comment]
No, I don't think this is a good idea. The natural shape is N x 2, not 2 x N. People can call np.transpose on the other case.

**Comment by henryiii** [comment]
> No, I don't think this is a good idea.

You just mean we should switch the order, not that setting ranges at a time is a bad idea, I believe. The canonical example then would be:

```python
h[:] = np.stack([uphist.allbins, uphist.allvariances], axis=1)
```

**Comment by HDembinski** [comment]
Yeah, sorry for being ambiguous, setting ranges at a time is of course desirable, the question is which shape to accept, N x 2 or 2 x N as in your example. The memory layout is N x 2, so the natural (and potentially faster) choice is to assign N x 2 shapes.
