### ISSUE TITLE
Port to boost::histogram multi-threaded storage

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#37]
How should we proceed with this? The develop branch now has support for multi-threaded fills for any axis and all dense storage types. It doesn't work yet for the unlimited_storage, this will come in the not so near future, because I expect it to be very difficult to get that right. I want to first get some experience with the current threaded capabilities.

Do you want to keep your current self-made multi-threaded storage for comparison or should I replace it with the boost::histogram one?

**Comment by HDembinski** [comment]
According to my tests, it is safe to always use the atomics even for single-threaded code. Therefore, there is no need to provide thread-safe and non-thread-safe storages.

**Comment by HDembinski** [comment]
By "safe" I mean it is as fast. The should be a minor performance penalty for when you use growing axes, but growing axis are anyway bad for performance so I doubt it is a problem.

**Comment by henryiii** [comment]
I think this is done.
