### ISSUE TITLE
Simpler rebin

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#372]
Currently, `bh.rebin` only works in a slice. I commonly rebin without slicing, so there should be a shortcut for that.
```
hist[::bh.rebin(2)] # ok, but the extra :: is annoying
hist[bh.rebin(2)] # does not work, but should

```

**Comment by henryiii** [comment]
I've thought about this before, see point 3 at https://github.com/scikit-hep/hist/issues/5#issue-583199839

The only problems are:

a) It mixes action and selection syntax, that is,

```python
# h is 2D, axes 0 is data and axes 1 is bool, such as signal/background
h[::bh.rebin(2), bh.loc(True)]
```
is rebinning one axes and removing the other. If we loosen the syntax to allow a raw action in place of choosing an item, it's a little less clear. Not too bad though.

b) It is harder to generalize to arbitrary functions. UHI allows anyone to write an indexer or a reducer. We can cause the normal ones to work properly (`sum`, `bh.rebin`, etc), but arbitrary reducers would have to use the `::<function>` syntax (at least if they didn't throw an error when applied to an axis).

I think I'm fine with the shortcomings and was planning to test this shortcut in hist first before seeing if it could be moved to boost-histogram. If you think you would like it, I can add it directly to boost-histogram (and then Hist gets it for free).

**Comment by HDembinski** [comment]
Ok

**Comment by henryiii** [comment]
This might be easy to enable during the full UHI impl. that I'm working (on and off) on.
