### ISSUE TITLE
Derivation Issue

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/boost-histogram#376]
https://github.com/scikit-hep/boost-histogram/blob/a12244f5daf81d5e619cefdd70d0d2ad859ca39d/src/boost_histogram/_internal/hist.py#L358

Should there be `super().__init__(*args, **kwargs)`?

**Comment by henryiii** [comment]
We still support Python 2, but yes, this is a mistake - It should be BaseHistogram.

**Comment by henryiii** [comment]
No, sorry, didn't read it fully. Yes, this is in Histogram, so this is correct. We can drop the insides of `super` when we drop Python 2 support, after 1.0.
