### ISSUE TITLE
ndim vs. rank

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#379]
Boost.Histogram uses "rank" to provide the number of axes in a histogram. NumPy uses `.ndim` to get the number of dimensions of a histogram. Moving between histograms and arrays is a little harder due to the different names (I just got caught telling Nino to use `.ndim` on a histogram). NumPy used to provide `np.rank`, but it was deprecated in favor of `np.ndim` in 1.9 (not 1.10, contrary to the 1.18 release notes claim) and removed in 1.18.

Options:

1. Support `.ndim` for normal boost-histogram, and `.rank` for cpp module. One way to do it, and all that.
2. Add `.ndim` and keep `.rank`, for maximum compatibility with both Boost.Histogram and NumPy.
    a. Python only
    b. Python + cpp module.
3. Keep as is.

@HDembinski, please advise.

**Comment by HDembinski** [comment]
Option 1 best, I agree.
