### ISSUE TITLE
Pandas (and other array package) improved compatibility

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#380]
boost-histogram currently doesn't work very well with Pandas DataFrames, requiring a `np.asarary` to work (and sometimes an explicit cast to a NumPy string datatype).
- [ ] My suggestion would be to do the `np.asarray` wrapping inside the Python fill wrapper, so that these can be simplified when using non-NumPy based arrays.

 - [x] You also can't setup categories from all iterables, like sets, but only from true `list`s, which is restrictive.

Actual usage:
```python
hist = bh.Histogram(
    bh.axis.StrCategory(list(set(skhep.file_project))),
    bh.axis.Integer(2018, 2021, underflow=False, overflow=False),
    bh.axis.Integer(2, 4, underflow=False, overflow=False),
    storage=bh.storage.Int64()
)

hist.fill(np.asarray(skhep.file_project, dtype=str),
          np.asarray(skhep.timestamp.dt.year),
          np.asarray(skhep.details_python.str[0].astype(int))
)
```

Ideal usage:

```python

hist = bh.Histogram(
    bh.axis.StrCategory(set(skhep.file_project)),
    bh.axis.Integer(2018, 2021, underflow=False, overflow=False),
    bh.axis.Integer(2, 4, underflow=False, overflow=False),
    storage=bh.storage.Int64()
)

hist.fill(skhep.file_project,
          skhep.timestamp.dt.year,
          skhep.details_python.str[0].astype(int)
)
```

**Comment by HDembinski** [comment]
I agree, fill should accept any array-like sequence and use `np.atleast_1d` to convert it.

**Comment by HDembinski** [comment]
I also agree on Category accepting any sequence.

**Comment by henryiii** [comment]
We already `forcecast` in PyBind11, so `np.ascontiguousarray` shouldn't be necessary, but probably wouldn't hurt. It just moves where the conversion happens - if a copy is made, it should (I think) become contiguous at the same time.

**Comment by henryiii** [comment]
This is not supported still by weights and probably samples - it should be, though. Reported by @meliache on Scikit-HEP Gitter.
