### ISSUE TITLE
Slices of AxesTuple should return AxesTuple

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#383]
The `AxesTuple` is lost after slicing, this leads to some unintuitive asymmetries.

```py
import boost_histogram as bh

h = bh.Histogram(bh.axis.Regular(10, 0, 1))
type(h.axes) == "boost_histogram._internal.axistuple.AxesTuple"
type(h.axes[:1]) == "tuple" # should return another AxesTuple

h.axes.centers[:1] # ok
h.axes[:1].centers # bummer, does not work, but should
```

**Comment by henryiii** [comment]
Oops, good catch!

**Comment by HDembinski** [comment]
You can see that we are making heavy use of bh in our analysis. :) My PhD student became very fluent with it very quickly, a good sign.

**Comment by henryiii** [comment]
Wow, this enables a really cool feature. There's a subtle difference between the shapes of the array-based methods; when you slice after the axes, you get the original dimensionality. When you slice before the axes, you get the dimensionality of the slice! So `h.axes.centers[1:3]` will have shapes (1, X, 1, ...), (1, 1, Y, ...) and `h.axes.centers[1:3]` will have the shapes (X, 1), (1,  Y). So, for plotting, the later is probably the most natural and wasn't trivially available before. If you are working within a larger context (say, computing projections from a 4D cylindrical histogram to a flat surface, such as I did in my thesis work), keeping the original shapes is more natural.
