### ISSUE TITLE
Indexing categories

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#387]
When filling, an int or str category will put values not in the axes either in a new bin (growth), a flow bin, or ignore it if overflow is off. However, the Python index method does the same thing - for example:

```python
h = bh.Histogram(bh.axis.StrCategory(["a", "b"]))
h.fill(["c"])
print(h[bh.loc("d")]) # Returns 1.0
```
Also,  if growth was on, this will not grow the axes, though at least one user expected that in the past.
Should Python indexes into non-existing string or int categories throw a TypeError or KeyError? I think this would be less error-prone. You could still use `bh.overflow` to access the flow bin explicitly.

Unlike axes with both an underflow and overflow, the categories represent a set of items, and Python tools for this sort of thing (like a dict) generally throw errors when you try to access a non-existent item (but not when setting it, so fill is still consistent).

@HDembinski ?

**Comment by HDembinski** [comment]
Throwing a ValueError or KeyError may help.

**Comment by HDembinski** [comment]
I am sure which one. A histogram with a category axis is not a dict, and we should not stress that analogy, so I am rather leaning toward ValueError.

**Comment by henryiii** [comment]
As you correctly inferred, I meant ValueError above, not TypeError. :)

Let me check a couple of other packages, specifically Pandas, to see what they throw (when I'm not on iOS, Pythonista doesn't include Pandas, sadly).

**Comment by HDembinski** [comment]
Good idea.

**Comment by henryiii** [comment]
Pandas does seem to throw a KeyError, both for a DataFrame:

```
d = pd.DataFrame({"col_one": [1]})
d["col_two"] # throws a key error
```

Or for a Series (which is arguably closer to what we have):

```python
s = pd.Series([1,2,3], ["a", "b", "c"])
s["d"] # Throws key error
```

**Comment by henryiii** [comment]
Xarray (from the SciPy tutorial) also uses KeyError (though it's using Pandas Indexers in the backend, so not shocking that it matches Pandas). Even for floating point coordinates. Xarray is very close to what we do. I would vote for KeyError.

**Comment by HDembinski** [comment]
Ok.

**Comment by nsmith-** [comment]
Just leaving a comment to say I ran into this (unexpected to me) behavior and look forward to the `KeyError`.
