### ISSUE TITLE
Boolean should be reducible

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/boost-histogram#395]
There might be a bug in BH:

```python
fro boost_histogram import bh

h = bh.Histogram(bh.axis.Boolean(), bh.axis.Boolean()).fill(
            [True, True, True, True, True, False, True],
            [False, True, True, False, False, True, False],
        )

true_only = h[:,  bh.loc(True)] # should work
h[0, :] # Should also work
```

I think this should work just like `Integer` axes and `h` should be reducible. But it does not.

**Comment by henryiii** [comment]
I've simplified the code a bit above, since it's visible with 2D axes as well (but not 1D). @HDembinski, is this a missing constructor in Boost.Histogram, perhaps?

**Comment by HDembinski** [comment]
There is currently no reduce ctor, right. One cannot further reduce a boolean axis.

**Comment by HDembinski** [comment]
More detail: Reducing in C++ does not change the axis type. The type of a boolean axis is state-free, it is fixed to a size of two. Therefore reducing is really technically not possible without changing the reduction framework. Maybe you can solve this in the Python layer?

**Comment by HDembinski** [comment]
One alternative for you is to not use the C++ implementation of boolean, but make Boolean just a specially configured Integer axis with a size of 2 and no flow bins. The speed gain of the C++ boolean class should be small compared to this and there is no additional compile-time cost.

**Comment by henryiii** [comment]
I really just need "pick" - a way to select either True or False and then remove the axis but leave the others. The other axes use reduce to select just one bin, then use project to remove the axis. Maybe we could 0 out one of the two bins, then sum over both?

**Comment by henryiii** [comment]
I could make this a fake subclass of Integer, and then it would be distinguishable from `Integer(0,2,*flow=False)`, that could work. I rather liked having the bool fill, since that might be faster for the common case of passing in a bool array (but we can keep that).

**Comment by HDembinski** [comment]
I think it will not be noticable. In my tests of the indexing with integer and boolean, I see almost no difference, because the integer axis is already so fast. Type conversion from int to bool and vice versa - if it can be inlined - is a no-op in C++.

**Comment by henryiii** [comment]
Temporarily fixed for now. We can improve in 1.0.
