### ISSUE TITLE
NumPy ND return 

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#405]
NumPy predates the Python 3 extended unpacking syntax, that is,

```python
bins, *edges = ...
```

Was not available. So the histogramdd function packs the remaining items. We probably need to fix the numpy.histogramdd function, and we need to think about the to_numpy method. I think we could have an argument that changes to the dd format, and keep the current format for consistency if not passed. Any automatic changes based on ndim are inconsistent, and also not how NumPy itself chose to go (they do not auto switch, they have separate functions).

See https://github.com/scikit-hep/uproot/issues/502

**Comment by HDembinski** [comment]
Ok, let's take the modern approach then.

**Comment by henryiii** [comment]
Solved in #406
