### ISSUE TITLE
AxesTuple names

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#409]
Currently, a rather odd naming scheme is employed for methods/properties that access Axis in AxesTuple. If the return value is a matrix, the method is (edit: already) pluralized, like "centers". However, if it is a tuple, then it is not make plural, like "extent" and "size". While not having a difference here at all is rather handy, it's not clear:

```python
assert h.axes[2].size == 15
assert h.axes[2:3].size == (15,)
```

You don't have to change the name from the first line to the second line, but the item it return is not the same shape - it's a tuple. It would probably be better to pluralize all methods/properties:

```python
assert h.axes[2].size == 15
assert h.axes[2:3].sizes == (15,)
```

@HDembinski , what do you think? Should this be changed for 1.0 or is it better the way it is?

**Comment by henryiii** [comment]
Slight change - I realize that the method name is never changed, it just started plural in the matrix case. That's better. What do you think, though, should accessing methods on the axes tuple always be pluralized, or always match the original method name? (IE, should `h.axes[0].extent` be `h.axes.extent[0]` or `h.axes.extents[0]`?

**Comment by HDembinski** [comment]
How about using numpy style `.shape` instead? I worry that `.size` and `.sizes` will be confusing for someone who is not aware of the details, the "s" is easy to overlook.

**Comment by HDembinski** [comment]
I think I would prefer the AxesTuple to have the same method names as the individual axis types, even if those return different types.

**Comment by henryiii** [comment]
Okay, sounds good. Will keep as is.
