### ISSUE TITLE
Trouble dividing histogram np.float64 and bin widths

### ISSUE THREAD

**Issue by Popinaodude** [scikit-hep/boost-histogram#435]
Filling a histogram like 
`hist = bh.Histogram(bh.axis.Regular(30, 1, 500, transform=bh.axis.transform.log))`
and then trying to scale the histogram like `hist /= np_float` or `hist = hist / np_float` where `np_float` is of type np.float64 returns the error:
`ValueError: Number of dimensions 0 must match histogram 1`.
This is an issue as numpy often returns float64 values from calculations on arrays

Also, the line `hist = hist / hist.axes.widths` returns the error:
`AttributeError: 'Histogram' object has no attribute 'extent'`
I feel like dividing bin entries by bin widths should be a smooth one-line deal? In-place division works with a regular numpy array

Is this a misunderstanding on how to use the library on my part?

**Comment by henryiii** [comment]
@HDembinski Let's try to get the fix in for this before releasing.

**Comment by henryiii** [comment]
There are two problems here, but I think they are actually the same problem. Histogram division with arrays should be handed off to the view, but that's not happening here like it's supposed to be. I'll let you know when I have a fix.

**Comment by henryiii** [comment]
Sorry, once I improved the error reporting, the second problem becomes more obvious; you need `hist / hist.axes[0].widths`. More generally, in 0.10.1 (releasing soon) you can do: `hist.axes.widths.prod(axis=0)` to multiply along axis 0 of the array (which is just a single value for 1D, but for ND histograms, this will correctly compute the area/volume/etc). I'm making a PR with fixes now.

**Comment by Popinaodude** [comment]
Ah, so the axis always has to be specified even for a 1D histogram, thanks! While I wait for a fix the first problem is easily worked around just by doing `float(np_float64)`. I appreciate the speedy replies!

**Comment by henryiii** [comment]
Yes, it's the same API regardless of the number of dimensions. Getting in the habit of multiplying the 0 axis (either by the trick above, or by using `functools.reduce(operator.mul, hist.axes)`, is good, though, because that formula works for ND.
