### ISSUE TITLE
Scalar numpy types handled incorrectly in fill method

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#452]
The fill method does not broadcast correctly in all cases.
```py
import boost_histogram as bh
import numpy as np

r = bh.axis.Regular(5, 0, 1)
h = bh.Histogram(r, r)
h.fill(1, [1, 2]) # ok
h.fill(np.float64(1), [1, 2]) # fails
```
It not only does not work, but the error message is also very confusing:
`ValueError: spans must have compatible lengths`

**Comment by henryiii** [comment]
A few notes before a proper fix (tomorrow), the issue is in `_fill_cast`:

* `np.ascontiguousarray` turns scalars into 1 element arrays.
* `np.isscalar` might be useful here

**Comment by patrickbryant** [comment]
I have found a similar broadcasting issue when filling a StrCategory histogram with an array of weights:

```
import boost_histogram as bh
r = bh.axis.StrCategory([])
h = bh.Histogram(r, r, storage=bh.storage.Weight())
h.fill('test','this',weight=1) # ok
h.fill('test',['this','error'],weight=[1,2]) # ok
h.fill('test','this',weight=[1,2]) # fails
```

This is with boost_histogram version 1.3.2
