### ISSUE TITLE
Severe bug in axis.Variable

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#468]
This should never possibly be happening:
```
import boost_histogram as bh
import numpy as np
bh.axis.Variable([1, 2, np.inf])
```
This produces `Variable([1, nan, inf])`

**Comment by HDembinski** [comment]
How is 2 changed to nan???

**Comment by henryiii** [comment]
Wow, that's _really_ weird. Verified locally. [1,2,3,np.inf] gives `[1,2,nan,inf]`. And, `float("inf")` does the same thing without NumPy.

**Comment by HDembinski** [comment]
I looked into the boost-histogram and the Boost Histogram code, everything looks innocent. ???

**Comment by HDembinski** [comment]
Ah, you say it is a bug in numpy!?

**Comment by henryiii** [comment]
No, I'm just saying you can write `float("inf")` and skip the usage of NumPy. It's a bug in Boost.Histogram, as it has to be, as we don't touch this:

```cpp
#include <iostream>
#include <vector>
#include <cmath>
#include <boost/histogram.hpp>
#include <boost/histogram/ostream.hpp>


namespace bh = boost::histogram;

int main() {
    std::vector<double> xarr = {1, 2, 3, INFINITY};
    bh::axis::variable<> x(xarr, "x");
    std::cout << x << std::endl;
}
```

```
variable(1, 2, -nan, inf, metadata="x", options=underflow | overflow)
```

See https://wandbox.org/permlink/YqOx4gaS88Wj3wMI

**Comment by henryiii** [comment]
I'm guessing it does some calculations on the edges and somehow this breaks when infinity is at one end? Seemingly only the upper end? Really weird bug, though!

**Comment by HDembinski** [comment]
Yes, I just got the same with godbolt.

**Comment by HDembinski** [comment]
btw, in c++17
```c++
#include <boost/histogram.hpp>
#include <boost/histogram/ostream.hpp>
#include <iostream>
#include <limits>

using namespace boost::histogram;

int main() {
    auto a = axis::variable{1., 2., 3., std::numeric_limits<double>::infinity()};
    std::cout << a << std::endl;
}
```

**Comment by henryiii** [comment]
My brain is hardwired to C++14 in boost-histogram. :P But much nicer and properly typed. :)

**Comment by HDembinski** [comment]
I am not going to open an issue in boostorg/histogram, because I am going to fix this right now...

**Comment by HDembinski** [comment]
... or maybe you want to keep this open for reference, but it is not a bug in boost-histogram.

**Comment by henryiii** [comment]
If you can refer to this when you fix it, we can close it then. Since you have admin rights here, you can even put "closes <reference to issue>" in the commit or PR and it will close (just put a fully qualified reference there, obviously, `scikit-hep/boost-histogram#468`).

**Comment by henryiii** [comment]
I'm curious to see the fix :)

**Comment by HDembinski** [comment]
The bug is here:
https://github.com/boostorg/histogram/blob/91e32ce17c98518039c291621dcf19ae09cb74cb/include/boost/histogram/axis/variable.hpp#L178
```c++
return (1.0 - z) * vec_[k] + z * vec_[k + 1];
```
0 times infinity is NaN.

**Comment by HDembinski** [comment]
The partially good news is that the histogram itself would have been correct.

**Comment by HDembinski** [comment]
Can we make a minor patch release for this fix? I am glad that I seem to be the one to find my own bugs first, god I hate bugs.

**Comment by henryiii** [comment]
Yes, I think pybind11 2.6.1 will be out soon, so we can bump both and release in a couple of days?

**Comment by HDembinski** [comment]
Ok, I can use develop in the meantime.

**Comment by henryiii** [comment]
Okay. Let's bump the submodule, add a test just to be sure, and add a changelog entry. I can do it a little later today.

**Comment by HDembinski** [comment]
I am good, releasing in a couple of days is fine.
