### ISSUE TITLE
Unclear how to access overflow and underflow bins for multidimensional histograms?

### ISSUE THREAD

**Issue by KeanuGh** [scikit-hep/boost-histogram#469]
I'm trying to access the over- and under-flow bins for a 2d histogram. 
`hist.axes[i].view()` returns an array of values not including the flow bins, so how do I access them? I've tried all sorts of combinations like `hist[{0: underflow}]` or the like but it's not like a multidimensional histogram has only one over and underflow bin per axis.

As well as this, how is accessing overflow and underflow bins different for different kinds of storages? I've found you need to access the `.value` for weighted bins in 1D histograms but how does this carry over for multiple dimensions?

I'm asking because I'm writing a script that converts from boost-histogram histograms to ROOT histograms and back since I couldn't find anything online to do it. If it turns out one does exist please let me know!

**Comment by henryiii** [comment]
You can do `hist.axes[i].view(flow=True)`, which returns all the flow bins too.

**Comment by henryiii** [comment]
Simple storages return raw numpy arrays. Accumulator storages return structured dtypes wrapped in a view that makes accessing the values simpler. There is no way to universally get the ".values" from both a weighted histogram and a simple histogram, but there might be after #423.

**Comment by henryiii** [comment]
There are no changes when going to multiple dimensions. You just get ND arrays instead of 1D arrays.

**Comment by KeanuGh** [comment]
Ah, thanks a lot for the help! I'm looking forward to the update :)
