### ISSUE TITLE
[BUG] Test histogram indexing results in AssertionError

### ISSUE THREAD

**Issue by kgizdov** [scikit-hep/boost-histogram#500]
**Describe the bug**
As the title says. Running the automated tests gives results in 1 failure about the histogram indexing assertions.
**Steps to reproduce**
Environment is Arch Linux x86_64, GCC 10.2, Boost 1.75, Python 3.9.1, testing with:
```bash
PYTHONPATH=${PYTHONPATH}:./build/lib.linux-x86_64-3.9 pytest
```
results in:
```python
=================================== FAILURES ===================================
_____________________________ test_one_sided_slice _____________________________

    def test_one_sided_slice():
        h = bh.Histogram(bh.axis.Regular(4, 1, 5))
        h.view(True)[:] = 1

        assert h[sum] == 6  # 4 (internal bins) + 2 (flow bins)
>       assert h[bh.tag.at(-1) : bh.tag.at(5) : sum] == 6  # keeps underflow, keeps overflow
E       assert 4.0 == 6

tests/test_histogram_indexing.py:213: AssertionError 
```

**Comment by henryiii** [comment]
This is a bug in Boost.Histogram that was patched, but didn't make it into the release. We use a checkout just after the release of 1.75.  CC @HDembinski

**Comment by henryiii** [comment]
There is an issue where an installed Boost overrides our internal boost headers. Is it possible to build the package without Boost pre-installed? Not sure how Arch works, if you can't control other installed packages, I might have to see if I can fix the path ordering.

**Comment by henryiii** [comment]
I'll look into the path ordering issue; I assume you got the submodules to work? The problem is the path to Python.h gets added before our own paths, and if Boost sits in the same places as Python.h, the system Boost overrides our headers, so you get the unpatched 1.75 Boost.Histogram, with the slicing bug.

**Comment by kgizdov** [comment]
No need. Can you give me the commit or diff that fixes boost? Even better if there is a relevant issue somewhere?

**Comment by kgizdov** [comment]
this one https://github.com/boostorg/histogram/issues/305 ?

**Comment by henryiii** [comment]
I believe it's https://github.com/boostorg/histogram/pull/302

**Comment by kgizdov** [comment]
Thanks. I will update the relevant packages to address this.

**Comment by HDembinski** [comment]
@kgizdov Thank you for the quick fix.

**Comment by henryiii** [comment]
Looks like boost-histogram is now in ARCH, I see in the recent packages:

https://archlinux.org/packages/community-testing/x86_64/python-boost-histogram/

:)

**Comment by kgizdov** [comment]
Yes, I put it there. But it's in `[testing]` until [this bug](https://bugs.archlinux.org/task/69612?project=1&string=boost) is resolved

**Comment by kgizdov** [comment]
@HDembinski there was not quick fix. I've pinged the maintainer of boost on Arch and waiting for them to hopefully have time to patch it in manually. I would much prefer we had an official bug-fix release, so that the fix is painless on our side.

**Comment by HDembinski** [comment]
Boost does not do intermediate releases for small things like this. The fix will be included in the next major release.

**Comment by HDembinski** [comment]
@henryiii Isn't the real bug in the build system? The build should always choose the local boost over the system boost...

**Comment by henryiii** [comment]
I believe @kgizdov wants to use the system versions of things (?) (he's explicitly adding boost and pybind11 from ARCH). Packagers usually hate internal dependencies. Though it's safe for header only dependencies in _most_ cases. AFIACT, the submodules are not being included in the package, so order doesn't matter?

I want to verify or fix the ordering issue before calling this closed, though, as I think I've noticed it being wrong before. :+1:

**Comment by henryiii** [comment]
Scrolling through the history, it looks like there's a patch release roughly once every 4-5 years or so. Kind of afraid to know what was bad enough to trigger a patch release! I think the next release is around mid April.

**Comment by kgizdov** [comment]
@henryiii Is this a header only dependency on boost? If so, I'd like to point out I didn't see that mentioned anywhere. Maybe I missed it.

Including the header-only dependency on some super mega custom version of boost (or anything else for that matter) is absolutely fine by me as long as it has zero runtime side effects. Looking at it now the binary doesn't seem to link to any boost libs, so should be fine.

**However**, in such a case, this becomes a more serious issue. First of all, I would have to depend on the submodules again and they are currently completely broken for me. So we'd have to fix that first #499. Then there's the issue when the built-in boost header eventually develops a bug - you would be responsible for fixing it, which is extra work on your part for little to no benefit. 

Thus, I propose, If you're gonna force me to use that header, make it configurable, so when it eventually breaks I can manually switch to latest system one without bugging you.

@HDembinski I understand that this is policy. But every time I hear this from an upstream I just cringe. :(

**Comment by henryiii** [comment]
> Is this a header only dependency on boost? 

https://github.com/scikit-hep/boost-histogram#source-builds

It's not a custom version, it's 1.75 for all Boost libraries except Boost.Histogram, which is slightly ahead of the official release, due to needed a patch that didn't make it before release. We only use official Boost.Histogram sources, but due to the fact we are a heavy user of Boost.Histogram, we may find bugs not normally hit by "regular" users, so we may need a patch that was post-release. That should be slowing down, and I'm hoping 1.76 will be exactly on the official version. I haven't worried about adding such a toggle for system versions since we haven't been able to use them.

For #499, we are using completely normal relative includes, which have been around in git since at least 2011. What exactly are you trying there?

Actually, what about using the SDist from PyPy? That already has the includes and the version file in it.

**Comment by henryiii** [comment]
Are you following https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git_submodules ?

**Comment by henryiii** [comment]
Also, you should remove the dependency on boost-libs, maybe you already gathered that.

**Comment by HDembinski** [comment]
Boost.Histogram on which this Python library is build, is header only. It is one of the first things mentioned on the Github front page.

**Comment by kgizdov** [comment]
@henryiii 
All this is true. As I said, probably missed it on the project main page. Indeed, it is quite far down and I was skimming. No problem there.

I'm not saying it's a custom version, I'm saying even it if was, not a problem.

The relative includes are fine, but for me they only work with SSH, which makes them not work in the build environment, as I mentioned previously. I am investigating why on my end as well. However, I have not had this problem with any of the other git packages in have. This is why I'm saying it should be looked at. It is why initially I though they were private repos as they were not reachable.

The package is in `[testing]` for a reason. It will be done right before release.

Pypy sources are not ideal in my opinion for other reasons, but if all else fails, I would do that, yes. I am however trying to reproduce the software from scratch, this is why I prefer GitHub.

**Comment by henryiii** [comment]
This is how most projects with submodules work, such as [Boost](https://github.com/boostorg/boost/blob/master/.gitmodules) itself, and others. You know know beforehand if a user needs SSH or HTTPS, so putting an absolute URL to either one is wrong, and causes issues.

Are you cloning with `--recurse-submodules`? What is the contents of your `.git/config` file (in relation to the submodules)? It should get populated with the correct paths, and you can change it (in modern Git) with `git submodule set-url [--] <path> <newurl>`. If git loses track of "origin", then it doesn't know where to clone the submodules from.

Building from an SDist is reproducing the software from scratch, as well. I'm happy for this to be solved via git, just noticing that Arch says "Git submodules are a little tricky to do. The idea is to add the URLs of the submodules themselves directly to the sources array and then reference them during prepare(). " -  it looks like Arch tooling does't handle submodules very elegantly.

**Comment by kgizdov** [comment]
OK, I've developed a new tool to deal with the dependencies quirks on our side.
