### ISSUE TITLE
[BUG] Missing dependancy for v.1.0.0

### ISSUE THREAD

**Issue by naidoo88** [scikit-hep/boost-histogram#528]
**Describe the bug**

I upgraded to v1.0.0 from 0.11.1 using `conda update boost-histogram`.  
Upon trying to import boost_histogram I received the error 
```
ModuleNotFoundError: No module named typing_extensions
```
Manually installing this with `conda install typing_extensions` resolved the issue.  

Just wanted to flag this up in case it was missing from the dependencies.

**Comment by henryiii** [comment]
Oops, that was added a while back. It shouldn't have been able to pass the conda tests without it, I would have thought. What version of Python? This should only affect 3.6 and 3.7, and is only an (easily fixable) issue with the conda recipe. Should have affected 0.13 and maybe 0.12 too.

**Comment by henryiii** [comment]
Oops, no, I'm wrong, it's missing from the main setup too. That's why conda was okay with it. I guess typing_extensions is so common (and very likely required by pytest), making it hard to detect the missing spec.

**Comment by naidoo88** [comment]
> It shouldn't have been able to pass the conda tests without it, I would have thought.
I had thought the same, but have a rather rudimentary understanding still of the inner workings of conda.  

I'm using Python 3.7.9 in the conda environment.

No worries at all if this is some conda related issue.  It is indeed very easily fixable!  Just wanted to flag  it in case it was helpful  :+1:

**Comment by naidoo88** [comment]
Ah, cracking :) 

> Oops, no, I'm wrong, it's missing from the main setup too. That's why conda was okay with it. I guess typing_extensions is so common (and very likely required by pytest), making it hard to detect the missing spec.

Ah, cracking!  Indeed, and no harm done or time lost :)

**Comment by henryiii** [comment]
> No worries at all if this is some conda related issue

Nope, it's missing here too. So therefore yes worries. :)
