### ISSUE TITLE
[DOCS] .reset() doesn't clear growing axis

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/boost-histogram#567]
Unsure if intended behaviour

**Comment by andrzejnovak** [comment]
I see, so it is intended. I was trying to make a copy of a histogram (while trying to make a sum on categorical axes) to assign new bins. 

I suppose it's unusual and if some groupby gets implemented unnecessary, but I'm not sure, if it's a completely illegitimate use

**Comment by henryiii** [comment]
This is clearly documented as "set counters to 0", so I think it's safe to close?

**Comment by henryiii** [comment]
(The name comes from Boost.Histogram, otherwise I'd suggest renaming it to `.clear()`)

**Comment by andrzejnovak** [comment]
Sorry, could you point to where it's documented? I couldn't find it with a cursory search.

**Comment by henryiii** [comment]
https://github.com/scikit-hep/boost-histogram#cheatsheet and https://boost-histogram.readthedocs.io/en/latest/usage/histogram.html#operations

**Comment by henryiii** [comment]
Can this be closed or is there an action that should still be taken?

**Comment by HDembinski** [comment]
I don't think that `.clear` would be any more obvious than `.reset`. Important is the documentation, not the name.
