### ISSUE TITLE
Methods vs. Properties

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#59]
I have mostly been leaving everything as similar as possible to Boost::Histogram. There are some possible Pythonizations we could investigate, especially for things that do not exist in the same form in Boost::Histogram.

* Names: Python expects classes to have CamelCase. Except for the standard library and numpy. I think we should stay lowercase to match Boost::Histogram, though the classes really can't map 1:1 to templated classes.
* Methods in Boost::Histogram: we can keep these the same or make them properties. Sometimes it is helpful to have a `flow=False` extra parameter, as well.
* Methods not in Boost::Histogram: some of these are there to make Python easier to write, such as `.centers()`. They might be slightly more pythonic as `.centers`, but some of these might have the option to have `flow=False`, so I'm inclined to leave them as methods.
* Settable methods: These are clear, they should be properties. Like `ind.content`.
* Names: Should indexed's setter `.content` or a `.contents` to set the value contained in the bin? There probably are other cases.

We should settle down on these before the release in a few days.

**Comment by HDembinski** [comment]
We need to set some rules and then follow them consistently.

1. Classes and functions should go by the same names.

2. Pure accessor methods can be properties, like .rank and .size. Methods which actually compute something should stay methods, even if they do not accept arguments (currently). As you said, it is more future-proof to use methods.

3. and 4. "Settable methods", are there any? I don't like .content for indexed and I don't like a Python version of indexed.

**Comment by HDembinski** [comment]
Boost-Histogram is not ready for a release, if by release you mean a version that is a fixed interface that we are not going to change in future versions. I have a couple of issues with the current interface of Boost-Histogram and those need to resolved before a release.

**Comment by henryiii** [comment]
By release, I mean an alpha version on PyPI that people can more easily test. It would come with alpha-status warnigns but we will need to get further testing from groups interested in trying boost-histogram. But we will try to provide a reasonably stable interface if possible - don't worry too much by the "few days", it might be 1-3 weeks, and that would be okay.

**Comment by HDembinski** [comment]
Ok, but there can be no release before we settle the open issues regarding the interface.

**Comment by HDembinski** [comment]
I think we can close this with the compromise:

Free functions in boost::histogram are also free functions here, and in addition there are methods with the same name attached to the histogram class. This way there is some interface bloat, but numpy is doing something similar so it is not all that surprising.

I understand that methods are useful for people who use IDEs with certain types of autocompletion. Since the C++ library uses free functions, however, the Python interface should also support that, to not put mental strain on people who use both the C++ and the Python interface.

**Comment by HDembinski** [comment]
Can we make histogram::rank and histogram::size into properties?

**Comment by henryiii** [comment]
Yes

**Comment by henryiii** [comment]
I *think* all these are changed/fixed, correct? Can we close?
