### ISSUE TITLE
[BUG] Undefined symbol when importing boost-histogram 1.1.0

### ISSUE THREAD

**Issue by KeanuGh** [scikit-hep/boost-histogram#609]
Undefined symbol when importing boost-histogram 1.1.0

**Steps to reproduce**
- Create new python venv via conda `conda create -n test_env`
- Install latest version of boost-histogram via pip `pip install boost_histogram`
- attempt import `python -c "import boost_histogram"`
- Error as below:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.conda/envs/test_env/lib/python3.9/site-packages/boost_histogram/__init__.py", line 1, in <module>
    from . import accumulators, axis, numpy, storage
  File "/home/user/.conda/envs/test_env/lib/python3.9/site-packages/boost_histogram/accumulators.py", line 1, in <module>
    from ._core.accumulators import Mean, Sum, WeightedMean, WeightedSum
ImportError:` /home/user/.conda/envs/test_env/lib/python3.9/site-packages/boost_histogram/_core.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv
```

Error does not happen with older versions:
```
$ pip install --upgrade boost_histogram==1.0.2
$ python -c "import boost_histogram"
$ 
```

Platform/OS: Arch Linux
Python version: 3.9.5

**Comment by henryiii** [comment]
The immediate fix should be to `conda install -c conda-forge boost-histogram`, but of course this should also work. I'll have to look into what changed; looks like it's not being audited correctly, guessing that's supposed to be in libstdc++ but it's using too new a version - actually, that doesn't seem right, arch should be newer than even the manylinux2010 gcc.

**Comment by KeanuGh** [comment]
Seems like you're right about the libstdc++ version wasn't correct because installing from conda-forge produces the following output:
```
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/user/.conda/envs/root_env

  added / updated specs:
    - boost-histogram


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libstdcxx-ng-9.3.0         |      h6de172a_19         4.0 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         4.0 MB

The following NEW packages will be INSTALLED:

  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-4.5-1_gnu
  boost-histogram    conda-forge/linux-64::boost-histogram-1.1.0-py39h1a9c180_0
  libgomp            pkgs/main/linux-64::libgomp-9.3.0-h5101ec6_17
  python_abi         conda-forge/linux-64::python_abi-3.9-2_cp39

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2021.4.13-~ --> conda-forge::ca-certificates-2021.5.30-ha878542_0
  certifi            pkgs/main::certifi-2020.12.5-py39h06a~ --> conda-forge::certifi-2021.5.30-py39hf3d152e_0
  libgcc-ng                                9.1.0-hdf63c60_0 --> 9.3.0-h5101ec6_17
  libstdcxx-ng       pkgs/main::libstdcxx-ng-9.1.0-hdf63c6~ --> conda-forge::libstdcxx-ng-9.3.0-h6de172a_19

The following packages will be SUPERSEDED by a higher-priority channel:

  openssl              pkgs/main::openssl-1.1.1k-h27cfd23_0 --> conda-forge::openssl-1.1.1k-h7f98852_0
```

So some of the dependencies aren't being sorted properly via pip

**Comment by henryiii** [comment]
Ahh, I think I see the problem - I bet the "install" phase was slow - it should be a second or two, not a minute or more - that means it is compiling. I accidentally disabled the manylinux2010 builds, and that was the only thing producing Python 3.9 wheels for linux - so there was no wheel, and conda build this from source with GCC 9, but GCC 9 was missing libstdc++ 9. The manylinux wheel is just fine with the libstdc++ on your system, so uploading that should fix the problem.

The upload just finished, can you try again?

**Comment by henryiii** [comment]
> `conda create env -n test_env`

`conda create -n test_env`, for anyone reading.

> So some of the dependencies aren't being sorted properly via pip

Pip can't force conda to install anything. You do not have the compilers by default (or even libstdc++, apparently) by default in a conda environment. Pip can't tell conda to do anything, so you ended up with your system compiler + conda python, which was linked against a (probably) newer libstdc++.

If you do need to build things in conda, you should install the conda compiler package. And boost-histogram (and most packages) should normally have wheels so you won't have to worry about compiling at all if you do mix them. But also, always try conda before you fall back on pip.

Thanks for finding this! It was a tricky thing to find, and was at the very least providing a non-optimal experience for Python 3.9 linux users (which are likely a bit rarer than 3.9 macOS/Windows users), and at the worst, not working.

**Comment by henryiii** [comment]
Does it work now? Can this be closed?

**Comment by KeanuGh** [comment]
Hi yes, this now works and can be closed

**Comment by henryiii** [comment]
Thanks!
