### ISSUE TITLE
[BUG] Throw error when filling Int64 with negative weight

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/boost-histogram#618]
```
import numpy as np
import hist

h = hist.Hist.new.Reg(50, -5, 5).Int64().fill(np.random.randn(100))
h.fill(3, weight=-1)
h.plot();
```

![image](https://user-images.githubusercontent.com/13226500/126985939-194704b1-9e6b-40a7-bcd7-95973bd07cb8.png)

Filling negative weights to the wrong storage type gives a silent error. This should either give a warning or just not be allowed at all.

**Comment by henryiii** [comment]
Fixed by #636, I think, but can add a test.
