### ISSUE TITLE
Apply clang-format to all files

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#62]
My editor is set up to apply clang-format automatically on each save. Some files are not clang-format, e.g. register_histogram.hpp. If I edit such a file, it creates a huge diff because of the formatting.

To prevent this, please clang-format all files once.

**Comment by henryiii** [comment]
This is supposed to be done already and is supposed to be checked by CI - will need to investigate!

**Comment by HDembinski** [comment]
Ok, good to know! :)

**Comment by henryiii** [comment]
The resolution seems to be use Clang-8, and Clang 7 is too old. Probably should be mentioned in the docs. (Technically, we follow unibeautify, though homebrew is usually in sync too).
