### ISSUE TITLE
[BUG] axis equality comparison errors with different types

### ISSUE THREAD

**Issue by jonas-eschle** [scikit-hep/boost-histogram#626]
**Describe the bug**

The equality comparison of the axis does not return False but errors (because the `__eq__` assumes that the other object supports the axis protocol)
`bh.axis.Regular(20, -3, 3) == []`

**Steps to reproduce**

```
import boost_histogram as bh

bh.axis.Regular(20, -3, 3) == object()
```

I already fixed it (checking for the attribute such as `Histogram` does) and added a test, fine if I make a PR with the fix?

**Comment by henryiii** [comment]
Sure, that would be great!
