### ISSUE TITLE
all pytest calls fail after rebasing to latest develop

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#63]
```
python3 -m pytest ../tests/test_histogram_internal.py
ERROR: usage: pytest.py [options] [file_or_dir] [file_or_dir] [...]
pytest.py: error: unrecognized arguments: --benchmark-disable
  inifile: /Users/hdembins/Code/boost-histogram/tests/pytest.ini
  rootdir: /Users/hdembins/Code/boost-histogram/tests
```
The current directory is a `build` folder inside the repo. `make test` also generates failures for each pytest.

My pytest version is 4.4.1. It was working fine on an older checkout of the develop branch.

**Comment by henryiii** [comment]
It requires you install `pytest-benchmark`. That is in the dev requirements, but needs to be more explicitly documented, probably.

**Comment by henryiii** [comment]
Edit: It's in the readme, should I add it more explicitly somewhere?

**Comment by HDembinski** [comment]
Sorry, I didn't read the README, I looked into CMakeLists.txt. Ideally CMakeLists.txt should check for the existence of pytest and pytest-benchmark and raise an error if it is not present when I run `make test`.
