### ISSUE TITLE
Find Python Package or combined python import

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#66]
It would be nice to have something like `find_python_package` that mirrors `find_package`. It would set `X_FOUND` and one can then conditionally add the test targets when all Python packages are available.
```
find_python_package(pytest)
find_python_package(pytest-benchmark)

if (pytest_FOUND AND pytest_benchmark_FOUND)
  enable_testing()
  add_subdirectory(tests) # or similar
else()
  message(STATUS "Tests disabled, please do `pip install pytest pytest-benchmark` to enable") # or similar
endif()
```

_Originally posted by @HDembinski in https://github.com/scikit-hep/boost-histogram/pull/64#issuecomment-491240190_

OR

Combine the packages in `python_import` and provide a combined error message.

**Comment by henryiii** [comment]
Is the current `python_import` function good enough? It doesn't exactly mimic `find_package`, but does print nice error messages, etc.

**Comment by HDembinski** [comment]
The current `python_import` cannot handle optional dependencies like `find_package`. It is ok, but it would be more elegant to have something that mimics `find_package` in behavior. Expected behavior:
```
find_python_package(pytest REQUIRED) # we must have pytest
# no need to check pytest_FOUND
find_python_package(pytest-benchmark) # we may have pytest-benchmark
if (pytest_benchmark_FOUND)
  # do stuff
endif()
```
There is nothing more for this function to do.

**Comment by henryiii** [comment]
At the moment, we don't have optional dependencies. `pytest-benchmark`, since you need it to import from it and disable it.

It would be kind of nice to have a aggregating version, I think, so it would print a single message "You should run pip install numpy pytest pytest-benchmark", which would look something like:

```cmake
python_import(numpy pytest pytest-benchmark)
```

**Comment by HDembinski** [comment]
> At the moment, we don't have optional dependencies. pytest-benchmark is required, since you need it to import from it and disable it.

It was just an example, but I don't understand what you mean by "need it to import from it and disable it"?

> It would be kind of nice to have a aggregating version, I think, so it would print a single message "You should run pip install numpy pytest pytest-benchmark", which would look something like:

Yes, but it would also be nice to have a command that looks and feels like a familiar CMake command :).

**Comment by henryiii** [comment]
I think the combination is more important, and this is not really like `find_package`, since it does not produce anything. I have in the past written `find_package` imitators (`find_modern_package`, specifically), but I think the combined version with a single "please install this" is better, since there's a lot (2-3 lines) of extra "junk" printed by the warning and it quickly hides the other things you need to install. This is user-facing, while the CMake command is not. I could be convinced otherwise, however, if you really like to mimic `find_package`.

**Comment by HDembinski** [comment]
No, I will insist on this.

**Comment by henryiii** [comment]
(I'll use this to remind me to add the combined version)
