### ISSUE TITLE
Don't allocate small objects

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#78]
Allocation of small objects is a performance killer. An allocation from the heap costs between O(100) and O(10000) cpu cycles. An allocation on the stack costs 1 cpu cycle. Therefore, small objects with short life-time should be allocated on the stack and not the heap.

Therefore, the following code is wasteful:
```
/// Get and remove a value from a keyword argument dict, or return a empty pointer
template <typename T>
std::unique_ptr<T> optional_arg(py::kwargs &kwargs, const char *name) {
    if(kwargs.contains(name)) {
        return std::make_unique<T>(py::cast<T>(kwargs.attr("pop")(name)));
    } else {
        return std::unique_ptr<T>();
    }
}
```
C++17 has std::optional for this and boost has boost::optional. This code should those facilities or simply return a pybind11 handle without casting. The handle can be null, so it can act as an optional thing without allocating anything new.

**Comment by HDembinski** [comment]
If you want to run benchmarks to check this claim of bad heap performance, be careful to do it correctly. On Linux, allocating an array of PODs with new will be "very fast", because the OS does not actually do anything yet. The actual allocation only happens when you write to this memory.

**Comment by henryiii** [comment]
Adding boost::optional adds a dependency, and this is something that should not happen "often", so paying a small cost should be okay. But it should be looked into.

**Comment by HDembinski** [comment]
It will hurt in timeit benchmarks of the fill performance in Python. fast-histogram is 25x faster than numpy for small arrays because it doesn't allocate a second array for the bin edges.

**Comment by henryiii** [comment]
Keep in mind that making Python objects makes small allocations too, and also pays a little extra cost as well in Python bookkeeping.

**Comment by henryiii** [comment]
Immediately reading everything into C++ structures, then working on those (possibly without the GIL) would probably be the fastest way to work. (Thinking of Python arguments here, but could be applied to other places with small allocations possibly) I'm not against adding `boost::optional` if it helps the design, as well. At the moment I'll be focusing on things needed for 0.5, feel free to work on it though!

**Comment by HDembinski** [comment]
> Keep in mind that making Python objects makes small allocations too, and also pays a little extra cost as well in Python bookkeeping.

Creating new Python objects, yes. I avoid creating new Python objects. Creating a py::None costs nothing, since the is only one allocated instance of None in a Python program anyway.

**Comment by HDembinski** [comment]
> Immediately reading everything into C++ structures, then working on those (possibly without the GIL) would probably be the fastest way to work.

I don't believe this is true and you would sacrifice single-thread performance.

**Comment by HDembinski** [comment]
I think this can be closed. I haven't noticed anything lately.
