### ISSUE TITLE
Don't include master header "boost/histogram.hpp"

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#80]
The master header "boost/histogram.hpp" includes almost all other headers. This causes all files in this project to be recompiled if any header in boost::histogram changes, even if they are not affected by this change. Some people in boost think we shouldn't even provide master headers because of this issue, but they are very useful to quickly get started and seems to outweigh the potential problems. This project should not include the master header, though.

**Comment by henryiii** [comment]
Agreed; it's just easier to start with developing with the main header at first. Once the files are fairly stable the correct includes can be used instead. This was always planned (but may not be on my master list). Thanks!

**Comment by henryiii** [comment]
@HDembinski You are welcome to change this at any time; at first I was not very familiar with where everything was in Boost.Histogram; I'm much more familiar with the structure now but you are an even better candidate ;)

**Comment by HDembinski** [comment]
Ok will do it at some point.
