### ISSUE TITLE
Move factory_meta stuff to Python

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#81]
I shouldn't have to recompile the code whenever this changes.
```
    // This factory makes a class that can be used to create histograms and also be used in is_instance
    py::object factory_meta_py = py::module::import("boost.histogram_utils").attr("FactoryMeta");

    m.attr("histogram")
        = factory_meta_py(m.attr("make_histogram"),
                          py::make_tuple(hist.attr("any_double"), hist.attr("any_unlimited"), hist.attr("any_weight")));
```

**Comment by henryiii** [comment]
You'll notice the current design does not allow any pure Python - it's a completely compiled extension in a single `histogram.so`. Moving to a mixed codebase will require renaming to something like `histogram/_histogram.so`), make the fullnames more complex, and will require handling folders. It can be done, but if I don't have to, I'd rather keep the single file, and have the pure python code in Hist.

**Comment by henryiii** [comment]
Ah, looking at #82, if there's significantly more Python code and it provides some benefit, then that would be a reason to restructure this.

**Comment by HDembinski** [comment]
I think this will benefit us greatly in the long run.

**Comment by HDembinski** [comment]
I use this scheme in pyhepmc and it not difficult to set up. It allows for more rapid development, since one doesn't have to recompile always.

**Comment by henryiii** [comment]
Follows #60.
