### ISSUE TITLE
[FEAT]: Add -latomic link arg for armv7l machines

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/boost-histogram#822]
As discussed with @henryiii in https://github.com/piwheels/packages/issues/341 for `boost-histogram` to build on armv7l machines (32-bit Raspberry Pis) the `-latomic` linker arg needs to be added. If this is acceptable, I have a working patch (https://github.com/piwheels/packages/issues/341#issuecomment-1377994407) that is committed on a branch and ready for me to PR.

This may not be of interest though as this is for a rather niche platform and Raspberry Pis are now capable of running a 64-bit OS which can just use `aarch64` wheels.

**Comment by henryiii** [comment]
I'd be happy to accept it, as long as it's understood to be a contributed level of support. I do have a pi or two I can test on, but I don't get them out very often. Also I'd prefer not to make a 1.3.3 or whatever's next just to support it, so it would be nice if the patch could be used for piwheels until a new version gets released for another reason.

**Comment by matthewfeickert** [comment]
> I'd be happy to accept it, as long as it's understood to be a contributed level of support.

Yup, wouldn't expect anything else.

> Also I'd prefer not to make a 1.3.3 or whatever's next just to support it, so it would be nice if the patch could be used for piwheels until a new version gets released for another reason.

SGTM. I can see if they can manually upload my wheels that work or if we can figure out how they can build with exporting `LDFLAGS`.

**Comment by matthewfeickert** [comment]
ping @henryiii if you have time to review in the next week.
