### ISSUE TITLE
Bin lifetime bug

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#89]
Found this issue in my presentation notes:

While axis.bin(X) usually works, axis.bins() may have corrupted bins. For example:

```python
import boost.histogram as bh
bh.axis.regular_log(10,1,5).bins()
```

```
[<bin [1.000000, 1.000000]>,
 <bin [1.000000, inf]>,
 <bin [inf, inf]>,
 <bin [inf, inf]>,
 <bin [inf, inf]>,
 <bin [inf, inf]>,
 <bin [inf, inf]>,
 <bin [inf, inf]>,
 <bin [inf, inf]>,
 <bin [inf, inf]>]
```

(varies randomly)

**Comment by HDembinski** [comment]
Yes, the bin types are views, so in `axis_to_bins` you make an array of these views. They become invalid once the regular axis is deleted. You need the nurse-patient mechanism to extend the life-time of the axis https://pybind11.readthedocs.io/en/stable/advanced/functions.html?highlight=nurse#additional-call-policies

Alternatively, axis_to_bins could return a numpy array set to the bin edges.

**Comment by HDembinski** [comment]
I think I would prefer to not expose the bins but rather return a suitable numpy array.

**Comment by HDembinski** [comment]
Besides, instead of returning a std::vector, which is then implicitly converted to a Python list by pybind11, it is better to create Python list directly and fill that. This avoid the allocation and deallocation of the temporary std::vector.

**Comment by henryiii** [comment]
The main use for me was a way to see what the axis represented. A nice `__repr__` would probably be just as good. And, of course, access to `.centers`, etc.

**Comment by HDembinski** [comment]
Fixed by removal :)

**Comment by henryiii** [comment]
A valid way to fix a bug. :)
