### ISSUE TITLE
[BUG] Integer axes do not function correctly with numpy 2.0 installed

### ISSUE THREAD

**Issue by lgray** [scikit-hep/boost-histogram#943]
with numpy 1.26.4:
```
>>> import boost_histogram as bh
>>> bh.axis.Integer(0,5)
Integer(0, 5)
```

with numpy 2.0:
```
>>> import boost_histogram as bh
>>> bh.axis.Integer(0,5)
Integer(5, 5)
```

This causes test failures in coffea and incorrectness in analysis using numpy 2.0. This is urgent.

**Comment by lgray** [comment]
@henryiii

**Comment by henryiii** [comment]
At USCMS. Will look at as soon as I can. Let me know if you have any more debugging insights. 0 turning into 5 is really odd.

**Comment by lgray** [comment]
I am at USCMS as well. Hopefully it's something simple. I don't really have time to dig that deep into it.

Issue where we found this in coffea: https://github.com/CoffeaTeam/coffea/issues/1112

**Comment by henryiii** [comment]
```pycon
Python 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boost_histogram as bh
>>> bh.axis.Integer(0,5)
Integer(0, 5)
>>> import numpy as np
>>> np.__version__
'2.0.0'
```

**Comment by lgray** [comment]
OK - looking again I had a skewed package on my laptop that was causing the issue. 

Trying to figure out why it was a problem in coffea's CI though.

**Comment by lgray** [comment]
OK - this was a bit of a red herring. Now that I've fixed up my local environment the issue seems to be some strange roundoff difference in np.histogram.
